/* Moduł: Metody pracy twórczej z dziećmi i młodzieżą, wykład 1: Specyfika.
 *
 * Źródło każdej pozycji (pole s):
 *   "S" slajd lub sylabus (domyślne, pomijane)
 *   "U" powiedziane ustnie na wykładzie
 *   "D" dopowiedzenie spoza wykładu (★). Egzamin próbny je pomija.
 *
 * Typy ćwiczeń (pole t):
 *   mcq    q, a[] (pierwsza odpowiedź jest poprawna), x
 *   tf     q, a (true/false), x
 *   cloze  q z luką ___, a[] (pierwsza poprawna), x
 *   type   q, a[] (akceptowane odpowiedzi), x
 *   which  q (sytuacja), a (numer zasady 1-10), x
 *   match  pairs[[lewo, prawo], ...]
 *   sort   q, cats[2], items[[tekst, 0|1], ...]
 */
Wykuj.registerModule({
  id: "mpt-w1",
  course: { id: "mpt", name: "Metody pracy twórczej z dziećmi i młodzieżą", short: "MPT", theme: "green", icon: "pencil" },
  number: 1,
  title: "Specyfika",
  lecturer: "dr Barbara Cichy-Jasiocha",
  term: "semestr zimowy 2026/2027",
  passing: "Obecność + test pisemny z pytaniami zamkniętymi. Trzeba uzyskać więcej niż 50% punktów.",
  passRatio: 0.5,

  principles: [
    "Prymat procesu nad efektem",
    "Psychologiczne bezpieczeństwo",
    "Aktywacja polisensoryczna",
    "Elastyczność struktury",
    "Metaforyzacja i projekcja",
    "Rytualizacja i ramy (setting)",
    "Ambiwalencja oporu",
    "Przekraczanie egocentryzmu, teoria umysłu",
    "Sprawczość i poczucie kontroli (LOC)",
    "Kanalizacja i sublimacja"
  ],
  /* Czym jest każda zasada: podpowiedź po odpowiedzi w pytaniach „która to zasada?”. */
  principleWhy: ["zasada 1: liczy się sam akt tworzenia, a nie estetyka gotowego dzieła",
    "zasada 2: klimat bez oceniania, zielony ołówek (zasoby zamiast błędów) i prawo do odmowy",
    "zasada 3: angażowanie wielu zmysłów naraz (glina, muzyka, zapachy, faktury)",
    "zasada 4: scenariusz to punkt wyjścia, a prowadzący jest gotowy na zwroty akcji",
    "zasada 5: o trudnych sprawach łatwiej mówić przez metaforę, bajkę albo rolę",
    "zasada 6: stałe rytuały i zmiana przestrzeni oddzielają zajęcia od zwykłej rzeczywistości",
    "zasada 7: opór jest naturalny, kryje się pod nim lęk, więc przyjmujemy go z empatią",
    "zasada 8: zadania wymuszają przyjęcie cudzej perspektywy",
    "zasada 9: wszystkie decyzje twórcze należą do dziecka („mój głos ma znaczenie”)",
    "zasada 10: napięciu i złości nadajemy twórczy kierunek zamiast je wygaszać"],

  units: [
    { id: "wstep", title: "Na start", sub: "Facylitacja, socjoterapia, zaliczenie", icon: "spark" },
    { id: "z1", title: "Proces nad efektem", sub: "Zasada 1 i projekcja myśli", icon: "spiral" },
    { id: "z2", title: "Zielony ołówek", sub: "Zasada 2: bezpieczeństwo i prawo do odmowy", icon: "pencil" },
    { id: "z34", title: "Zmysły i zwroty akcji", sub: "Zasady 3 i 4", icon: "hand" },
    { id: "z56", title: "Metafora i setting", sub: "Zasady 5 i 6", icon: "moon" },
    { id: "z7", title: "Opór", sub: "Zasada 7: „to jest bez sensu”", icon: "wall" },
    { id: "z8", title: "Cudza perspektywa", sub: "Zasada 8: egocentryzm i teoria umysłu", icon: "eye" },
    { id: "z9", title: "Czarne słońce", sub: "Zasada 9: sprawczość i LOC", icon: "sun" },
    { id: "z10", title: "Glina i bunt", sub: "Zasada 10: kanalizacja i sublimacja", icon: "flame" },
    { id: "tab", title: "Dzieci a młodzież", sub: "Tabela różnic", icon: "split" },
    { id: "mix", title: "Która to zasada?", sub: "Sytuacje z praktyki, wszystkie 10", icon: "dice" },
    { id: "boss", title: "Test końcowy", sub: "Wszystko z wykładu, 15 pytań", icon: "crown", boss: true }
  ],

  concepts: [
    { id: "facylitacja", u: "wstep", s: "U", term: "Facylitacja",
      def: "Sytuacja, w której obecność psychologa umożliwia rozpoczęcie i kontynuowanie procesu rozmawiania o trudnych emocjach.",
      sh: "obecność psychologa umożliwia rozmowę o trudnych emocjach" },
    { id: "facylitator", u: "wstep", s: "D", term: "Facylitator",
      def: "Nie jest ekspertem, który „naprawia”. Tworzy warunki, w których proces może zajść sam. Termin spopularyzował m.in. Carl Rogers (nurt humanistyczny).",
      sh: "tworzy warunki, by proces zaszedł sam (Rogers)" },
    { id: "socjoterapia", u: "wstep", s: "D", term: "Socjoterapia",
      def: "Grupowa forma pomocy psychologicznej dla dzieci i młodzieży z trudnościami emocjonalnymi i w relacjach. Opiera się na doświadczeniach korektywnych w bezpiecznej grupie.",
      sh: "grupowa pomoc oparta na doświadczeniach korektywnych" },
    { id: "cele-socjo", u: "wstep", s: "D", term: "Cele socjoterapii",
      def: "Terapeutyczne (odreagowanie, korekta przekonań o sobie i innych), edukacyjne (umiejętności społeczne, komunikacja) i rozwojowe (wspieranie potrzeb rozwojowych).",
      sh: "terapeutyczne, edukacyjne, rozwojowe" },
    { id: "zaliczenie", u: "wstep", term: "Zaliczenie przedmiotu",
      def: "Obecność plus egzamin: test pisemny z pytaniami zamkniętymi. Trzeba uzyskać więcej niż 50% punktów.",
      sh: "obecność + test zamknięty, ponad 50%" },
    { id: "proces", u: "z1", term: "Prymat procesu nad efektem",
      def: "Największą wartość terapeutyczną i rozwojową ma sam akt tworzenia, a nie produkt końcowy. Paradygmat „tu i teraz”. Cel: uwolnienie od presji perfekcjonizmu.",
      sh: "liczy się akt tworzenia, nie produkt" },
    { id: "projekcja", u: "z1", s: "U", term: "Projekcja myśli",
      def: "Przypisywanie obiektowi zewnętrznemu własnych stanów wewnętrznych. Uruchamia ją pytanie otwarte: „opowiedz mi o tym misiu, o czym on myśli?”.",
      sh: "przypisywanie obiektowi własnych stanów" },
    { id: "projekcja-psa", u: "z1", s: "D", term: "Projekcja w psychoanalizie",
      def: "Mechanizm obronny: przypisywanie innym własnych nieakceptowanych impulsów. Na teście trzymaj się definicji z wykładu (projekcja myśli, bez założenia obrony).",
      sh: "mechanizm obronny: moje impulsy przypisuję innym" },
    { id: "bezpieczenstwo", u: "z2", term: "Psychologiczne bezpieczeństwo",
      def: "Klimat bez oceniania: całkowite zawieszenie krytyki i ocen szkolnych. Twórczość wymaga odsłonięcia się, a to ryzyko emocjonalne (szczególnie u młodzieży).",
      sh: "klimat bez oceniania i krytyki" },
    { id: "zielony", u: "z2", term: "Zasada zielonego ołówka",
      def: "Zauważanie i wzmacnianie tego, co unikalne, nietypowe i ciekawe w pomyśle uczestnika (ZASOBY), zamiast wytykania błędów.",
      sh: "wzmacnianie zasobów zamiast wytykania błędów" },
    { id: "czerwony", u: "z2", term: "Czerwony ołówek",
      def: "Wytykanie błędów i tego, co „nie wyszło”. Tego psycholog unika.",
      sh: "wytykanie błędów i tego, co nie wyszło" },
    { id: "odmowa", u: "z2", term: "Prawo do odmowy",
      def: "Uczestnik zawsze może powiedzieć „NIE” i nie pokazywać pracy grupie, gdy temat jest zbyt intymny albo gdy po prostu nie chce.",
      sh: "zawsze można nie pokazać pracy grupie" },
    { id: "kierunek", u: "z2", s: "U", term: "Kierunek oceny",
      def: "Od oceniania nie da się uciec, więc psycholog świadomie zmienia jej kierunek: patrzy na zasoby (co się udaje), a nie na błędy.",
      sh: "oceniamy zasoby, nie błędy" },
    { id: "polisensoryka", u: "z34", term: "Aktywacja polisensoryczna",
      def: "Angażowanie wielu zmysłów jako zakotwiczenie w ciele: glina przy muzyce, malowanie na podłodze, zapachy, faktury. Wspiera regulację układu nerwowego i ekspresję.",
      sh: "angażowanie wielu zmysłów naraz" },
    { id: "snoezelen", u: "z34", s: "D", term: "Snoezelen",
      def: "Sala doświadczania świata wywodząca się z Holandii. Najbardziej znana realizacja środowisk wielozmysłowych (multi-sensory environments).",
      sh: "wielozmysłowa sala z Holandii" },
    { id: "elastycznosc", u: "z34", term: "Elastyczność struktury",
      def: "Podążanie za dynamiką grupy. Sztywny scenariusz to największy wróg kreatywności, prowadzący musi być gotowy na ZWROTY AKCJI. Twórczość staje się wentylem bezpieczeństwa.",
      sh: "scenariusz to punkt wyjścia, nie obowiązek" },
    { id: "metafora", u: "z56", term: "Metaforyzacja",
      def: "Bezpieczny dystans emocjonalny. Łatwiej opowiedzieć o „smutnym potworze, który zgubił się w lesie” albo zagrać buntownika niż powiedzieć wprost o swoich lękach.",
      sh: "bezpieczny dystans emocjonalny dzięki metaforze" },
    { id: "bajkoterapia", u: "z56", term: "Bajkoterapia",
      def: "Praca z opowieścią i metaforą, np. smutny potwór zgubiony w lesie. Rekomendowana dla dzieci (temat 9 sylabusa).",
      sh: "opowieść i metafora o trudnych emocjach" },
    { id: "drama", u: "z56", term: "Drama",
      def: "Odgrywanie ról, np. zbuntowanego bohatera albo zepsutej zabawki na deszczu. Trenuje przyjmowanie cudzej perspektywy; rekomendowana dla młodzieży.",
      sh: "odgrywanie ról i cudzej perspektywy" },
    { id: "setting", u: "z56", term: "Setting",
      def: "Jasne granice i rytuały oddzielające przestrzeń twórczą od „zwykłej rzeczywistości”. W psychoterapii: stałe ramy spotkań, czyli miejsce, czas i zasady.",
      sh: "stałe ramy: miejsce, czas, zasady, rytuały" },
    { id: "iskierka", u: "z56", s: "D", term: "Iskierka przyjaźni",
      def: "Rytuał rozpoczęcia: zabawa integracyjna w kręgu, w której uczestnicy kolejno przekazują sobie uścisk dłoni.",
      sh: "uścisk dłoni przekazywany w kręgu" },
    { id: "opor", u: "z7", term: "Ambiwalencja oporu",
      def: "Opór jest naturalnym elementem procesu, zwłaszcza u młodzieży. Kryje się pod nim lęk przed oceną, odrzuceniem przez grupę lub trudnymi emocjami. Psycholog nie walczy z nim, przyjmuje go z empatią.",
      sh: "opór jest naturalny, pod nim kryje się lęk" },
    { id: "ego-pozn", u: "z8", term: "Egocentryzm poznawczy",
      def: "Młodsze dzieci tkwią we własnej perspektywie i nie odróżniają swojej wiedzy od wiedzy innych (Piaget, stadium przedoperacyjne). Przykład: zasady zabawy, których nikomu nie powiedziały.",
      sh: "nie odróżnia swojej wiedzy od cudzej" },
    { id: "ego-adol", u: "z8", term: "Egocentryzm adolescentny",
      def: "Silne skupienie młodzieży na własnym przeżywaniu (opisał D. Elkind). Przejawy: wyobrażona publiczność i baśń osobista. Przykład: impreza z pryszczem.",
      sh: "młodzież skupiona na własnym przeżywaniu" },
    { id: "publicznosc", u: "z8", s: "D", term: "Wyobrażona publiczność",
      def: "Przekonanie, że wszyscy mnie obserwują. Przejaw egocentryzmu adolescentnego (Elkind).",
      sh: "przekonanie, że wszyscy mnie obserwują" },
    { id: "basn", u: "z8", s: "D", term: "Baśń osobista",
      def: "Przekonanie o własnej wyjątkowości. Przejaw egocentryzmu adolescentnego (Elkind).",
      sh: "przekonanie o własnej wyjątkowości" },
    { id: "tom", u: "z8", s: "D", term: "Teoria umysłu",
      def: "Zdolność przypisywania innym stanów psychicznych (przekonań, intencji) odmiennych od własnych.",
      sh: "inni mają inne przekonania i intencje niż ja" },
    { id: "marketing", u: "z8", s: "D", term: "Marketing doświadczeń",
      def: "Sprzedaje przeżycie, nie produkt. Zaaranżowane warunki prowadzą do projekcji, a projekcja do przeżycia. Ten sam mechanizm co w pracy twórczej, inny cel: sprzedaż zamiast wglądu.",
      sh: "sprzedaż przeżycia przez projekcję" },
    { id: "sprawczosc", u: "z9", term: "Sprawczość",
      def: "Poczucie wpływu na własny świat, budowane przez oddanie dziecku wszystkich decyzji twórczych: „ja decyduję, ja kreuję, mój głos ma znaczenie”.",
      sh: "„ja decyduję, mój głos ma znaczenie”" },
    { id: "loc", u: "z9", s: "D", term: "LOC (umiejscowienie kontroli)",
      def: "Koncepcja J. Rottera. Kontrola wewnętrzna: wyniki zależą ode mnie. Kontrola zewnętrzna: zależą od losu albo od innych.",
      sh: "umiejscowienie kontroli wg Rottera" },
    { id: "internalizacja", u: "z9", s: "D", term: "Internalizacja poczucia kontroli",
      def: "Uwewnętrznienie kontroli: przesuwanie się od przekonania „decydują za mnie” do „to zależy ode mnie”.",
      sh: "od „decydują za mnie” do „zależy ode mnie”" },
    { id: "czarne-slonce", u: "z9", s: "U", term: "Czarne słońce",
      def: "Nauczyciel plastyki poprawi: „słońce nie jest czarne”. Psycholog nie poprawia, tylko zastanawia się, dlaczego dziecko tak namalowało. Wybór koloru może nieść informację o przeżyciach.",
      sh: "psycholog nie poprawia, pyta: dlaczego tak?" },
    { id: "sublimacja", u: "z10", term: "Sublimacja",
      def: "Według nurtu psychodynamicznego najwyższa forma obrony przed lękiem: zamiana destrukcyjnej energii w konstruktywny lub ekspresyjny wytwór. Opisał ją Freud; Vaillant zalicza ją do mechanizmów dojrzałych.",
      sh: "destrukcyjna energia zamieniona w wytwór" },
    { id: "kanalizacja", u: "z10", s: "U", term: "Kanalizacja napięcia",
      def: "Nie wygaszamy napięcia, tylko nadajemy mu kierunek: glina do uderzania, buntowniczy tekst piosenki, taniec zamiast uciszania.",
      sh: "nadanie napięciu kierunku zamiast wygaszania" },
    { id: "homo-ludens", u: "tab", s: "D", term: "Homo ludens",
      def: "„Człowiek bawiący się” (J. Huizinga): zabawa jest pierwotnym źródłem kultury. Na niej opiera się motywacja dzieci.",
      sh: "człowiek bawiący się (Huizinga)" },
    { id: "vision-board", u: "tab", s: "U", term: "Vision board",
      def: "Metoda kolażu (manifestu) dla młodzieży: zdjęcia podpisane ideami, wartościami lub celami. Służy autorefleksji i budowaniu tożsamości.",
      sh: "kolaż-manifest z celami i wartościami" }
  ],

  exercises: [
    /* ---------- Na start ---------- */
    { u: "wstep", t: "mcq", s: "U",
      q: "Czym według prowadzącej jest facylitacja?",
      a: ["Sytuacją, w której obecność psychologa umożliwia rozmowę o trudnych emocjach",
          "Oceną postępów dziecka, którą psycholog robi po zajęciach twórczych",
          "Prowadzeniem zajęć ściśle według scenariusza przygotowanego wcześniej",
          "Rozwiązaniem problemu dziecka przez eksperta, który wie, co robić"],
      x: "Definicja z wykładu: facylitacja to sytuacja, w której obecność psychologa umożliwia rozpoczęcie i kontynuowanie procesu rozmawiania o trudnych emocjach.",
      w: ["Facylitacja nie polega na ocenianiu, tylko na umożliwieniu rozmowy.",
          "Sztywny scenariusz to wręcz wróg pracy twórczej (zasada 4).",
          "Facylitator nie naprawia, tylko tworzy warunki, w których proces zachodzi sam."] },
    { u: "wstep", t: "type", s: "U",
      q: "Sytuacja, w której obecność psychologa umożliwia rozpoczęcie i kontynuowanie procesu rozmawiania o trudnych emocjach, to…",
      a: ["facylitacja"],
      x: "Facylitacja: od łacińskiego facilis, „łatwy”. Psycholog ułatwia rozmowę samą swoją obecnością." },
    { u: "wstep", t: "tf", s: "D", q: "Facylitator to ekspert, który „naprawia” problem dziecka.", a: false,
      x: "Facylitator nie naprawia. Tworzy warunki, w których proces może zajść sam." },
    { u: "wstep", t: "mcq", s: "D",
      q: "Kto spopularyzował termin „facylitator” w nurcie humanistycznym?",
      a: ["Carl Rogers", "Jean Piaget", "Zygmunt Freud", "Julian Rotter"],
      x: "Carl Rogers, twórca podejścia skoncentrowanego na osobie (nurt humanistyczny), opisywał terapeutę jako kogoś, kto ułatwia, a nie naprawia.",
      w: ["Piaget badał rozwój poznawczy dzieci (egocentryzm poznawczy, zasada 8).",
          "Freud to psychoanaliza i sublimacja (zasada 10).",
          "Rotter to umiejscowienie kontroli, LOC (zasada 9)."] },
    { u: "wstep", t: "mcq", s: "D",
      q: "Socjoterapia to…",
      a: ["grupowa forma pomocy psychologicznej dla dzieci i młodzieży z trudnościami",
          "indywidualna terapia dorosłych, oparta głównie na rozmowie z terapeutą", "forma oceniania wytworów plastycznych dzieci przez psychologa",
          "metoda nauczania przedmiotów artystycznych w szkole podstawowej"],
      x: "Socjoterapia to grupowa pomoc psychologiczna dla dzieci i młodzieży z trudnościami emocjonalnymi i w relacjach. Opiera się na doświadczeniach korektywnych w bezpiecznej grupie.",
      w: ["Socjoterapia jest grupowa i dotyczy dzieci i młodzieży.",
          "Socjoterapia nie ocenia prac. W pracy twórczej ocena jest wręcz zawieszona (zasada 2).",
          "To pomoc psychologiczna, a nie dydaktyka plastyki."] },
    { u: "wstep", t: "mcq", s: "D",
      q: "Na czym opiera się socjoterapia?",
      a: ["Na doświadczeniach korektywnych w bezpiecznej grupie", "Na testach projekcyjnych i diagnozie psychologa",
          "Na nagradzaniu najlepszych prac w grupie", "Na sztywnym programie ćwiczeń do wykonania"],
      x: "Dziecko przeżywa w grupie coś innego niż dotąd (np. akceptację zamiast odrzucenia) i to „koryguje” jego przekonania o sobie i innych.",
      w: ["Socjoterapia nie jest diagnozą, tylko pomocą w grupie.",
          "Rywalizacja i rankingi są sprzeczne z klimatem bez oceniania.",
          "Sztywny program kłóci się z elastycznością struktury (zasada 4)."] },
    { u: "wstep", t: "match", s: "D",
      pairs: [
        ["Cele terapeutyczne", "odreagowanie, korekta przekonań"],
        ["Cele edukacyjne", "umiejętności społeczne, komunikacja"],
        ["Cele rozwojowe", "wspieranie potrzeb rozwojowych"]],
      x: "Terapeutyczne: odreagowanie i korekta przekonań. Edukacyjne: umiejętności społeczne i komunikacja. Rozwojowe: wspieranie potrzeb rozwojowych." },
    { u: "wstep", t: "mcq",
      q: "Jak zalicza się ten przedmiot?",
      a: ["Obecność i test z pytaniami zamkniętymi, powyżej 50% punktów", "Projekt grupowy i prezentacja na ostatnich zajęciach",
          "Egzamin ustny z losowanych pytań problemowych", "Esej zaliczeniowy na wybrany temat z sylabusa"],
      x: "Zaliczenie: obecność plus test pisemny z pytaniami zamkniętymi. Trzeba mieć więcej niż 50% punktów.",
      w: ["Nie było mowy o projekcie.",
          "Test jest pisemny i zamknięty, a nie ustny.",
          "Nie ma eseju, jest test zamknięty."] },
    { u: "wstep", t: "tf",
      q: "Wykład 1 pokazuje elementy, które odróżniają zajęcia twórcze z dziećmi i młodzieżą od standardowej edukacji i od pracy z dorosłymi.",
      a: true,
      x: "Tak. Cały wykład to 10 elementów specyfiki: co jest inne niż w szkole i inne niż w pracy z dorosłymi." },
    { u: "wstep", t: "cloze",
      q: "Prowadząca nazywa elementy specyfiki kluczowymi zasadami ___, które każdy przyszły psycholog powinien wdrożyć w praktyce.",
      a: ["psychopedagogicznymi", "psychoanalitycznymi", "dydaktycznymi", "artystycznymi"],
      x: "Kluczowe zasady psychopedagogiczne: łączą psychologię z pedagogiką.",
      w: ["Psychoanaliza pojawia się tylko przy sublimacji (zasada 10), nie w nazwie zasad.",
          "Dydaktyka to nauczanie, a tu chodzi o pracę psychologa.",
          "Zasady nie dotyczą sztuki, tylko psychologii pracy z dziećmi."] },
    { u: "wstep", t: "mcq", s: "D",
      q: "Co jest podstawowym narzędziem socjoterapii?",
      a: ["Metody twórcze: rysunek, drama, ruch", "Testy psychometryczne i kwestionariusze", "Wykłady i prezentacje dla grupy",
          "System kar i nagród za zachowanie"],
      x: "Socjoterapia pracuje metodami twórczymi (rysunek, drama, ruch), bo przez nie dzieciom łatwiej wyrazić to, czego nie umieją powiedzieć.",
      w: ["Testy służą diagnozie, a socjoterapia to pomoc w grupie.",
          "Wykład nie daje doświadczeń korektywnych.",
          "Kary i nagrody to behawioralne podejście, sprzeczne z klimatem bez oceniania."] },

    /* ---------- Proces nad efektem ---------- */
    { u: "z1", t: "mcq",
      q: "Co według prowadzącej ma największą wartość w pracy twórczej z dziećmi?",
      a: ["Sam akt tworzenia", "Estetyka gotowego wytworu", "Zgodność pracy z instrukcją", "Szybkość wykonania zadania"],
      x: "Prymat procesu nad efektem: największą wartość terapeutyczną i rozwojową ma sam akt tworzenia.",
      w: ["Estetyka to efekt, a liczy się proces.",
          "Instrukcja to sztywna struktura, a nie wartość pracy twórczej.",
          "Tempo nie ma znaczenia, bo liczy się samo tworzenie, tu i teraz."] },
    { u: "z1", t: "mcq",
      q: "Którą wypowiedź psychologa wykład podaje jako właściwą?",
      a: ["„Widzę, że użyłeś dużo czerwieni i mocno naciskałeś kredkę (opowiesz mi o tym?)”",
          "„Piękny rysunek! Widać, że masz talent i bardzo się postarałeś”", "„Hej, słońce nie jest czarne, popraw je na żółto, będzie ładniej”",
          "„Super, to na szóstkę, powiesimy go na tablicy w klasie”"],
      x: "Opis tego, co widać, bez oceny estetycznej, i zaproszenie do opowiedzenia. Tak realizuje się prymat procesu nad efektem.",
      w: ["To pochwała estetyki, czyli ocena efektu. Psycholog nie ocenia wyglądu.",
          "Poprawianie łamie zasadę 9: decyzja o kolorze należy do dziecka.",
          "Ocena szkolna i wystawianie prac to nastawienie na efekt."] },
    { u: "z1", t: "cloze", q: "Zasada 1 to prymat ___ nad efektem.",
      a: ["procesu", "produktu", "oceny", "talentu"],
      x: "Prymat procesu nad efektem: liczy się sam akt tworzenia, a nie gotowy produkt.",
      w: ["Produkt to właśnie efekt, który jest na drugim planie.",
          "Ocena jest zawieszona (zasada 2).",
          "Talent nie jest tu ważny, liczy się samo tworzenie."] },
    { u: "z1", t: "tf", q: "U dorosłych w pracy twórczej często liczy się produkt końcowy, np. książka, obraz czy projekt.", a: true,
      x: "Tak, wykład tak to porównuje: dorośli często tworzą dla produktu, a u dzieci i młodzieży największą wartość ma sam proces." },
    { u: "z1", t: "mcq",
      q: "Jaki jest cel tego, że psycholog nie ocenia estetyki dzieła?",
      a: ["Uwolnienie od presji perfekcjonizmu", "Przyspieszenie pracy całej grupy", "Ułatwienie wystawienia oceny końcowej",
          "Nauka poprawnej techniki plastycznej"],
      x: "Slajd: celem jest uwolnienie od presji perfekcjonizmu. Bez oceny dziecko może tworzyć swobodnie.",
      w: ["Tempo nie jest celem pracy twórczej.",
          "Oceny w ogóle nie ma, to klimat bez oceniania.",
          "Technika to cel lekcji plastyki, a nie pracy psychologa."] },
    { u: "z1", t: "mcq", s: "U",
      q: "Pytanie „co dostałeś z kartkówki?” prowadząca podała jako przykład…",
      a: ["nastawienia dorosłych na efekt (ocenę), a nie na proces", "dobrej praktyki facylitacji, która otwiera rozmowę",
          "pytania otwartego, które uruchamia projekcję u dziecka", "zasady zielonego ołówka, która wzmacnia zasoby"],
      x: "Pytamy o wynik zamiast o to, jak dziecko pracowało. To typowe nastawienie na efekt, przeciwne zasadzie 1.",
      w: ["To pytanie zamyka rozmowę na ocenie, a nie ją ułatwia.",
          "Projekcję uruchamia pytanie typu „opowiedz o misiu”, a nie o ocenę.",
          "Zielony ołówek patrzy na zasoby, a nie na stopień z kartkówki."] },
    { u: "z1", t: "mcq", s: "U",
      q: "Co według wykładu oznacza „wylewanie dziecka z kąpielą” w pracy twórczej?",
      a: ["Ocenianie tylko efektu bez analizy procesu", "Zbyt częste zmienianie scenariusza zajęć", "Pozwalanie dziecku na odmowę pokazania pracy",
          "Używanie zbyt wielu bodźców naraz"],
      x: "Oceniając sam efekt, tracimy to, co w pracy twórczej najcenniejsze, czyli proces. Stąd „wylewanie dziecka z kąpielą”.",
      w: ["Zmiana scenariusza to zaleta (zasada 4), a nie błąd.",
          "Prawo do odmowy to zasada 2, a nie błąd.",
          "Wiele zmysłów naraz to zasada 3, a nie błąd."] },
    { u: "z1", t: "type", s: "U", q: "Przypisywanie obiektowi zewnętrznemu własnych stanów wewnętrznych to ______ myśli.", a: ["projekcja"],
      x: "Projekcja myśli: dziecko „przenosi” swoje myśli i uczucia na misia, postać czy rysunek." },
    { u: "z1", t: "mcq", s: "U",
      q: "Prośba „opowiedz mi o tym misiu, o czym on myśli?” sprawia, że dziecko…",
      a: ["projektuje na misia własne myśli i mówiąc o nim, mówi o sobie", "uczy się poprawnie i dokładnie opisywać przedmioty",
          "zostaje ocenione za jakość swojej wypowiedzi", "traci zainteresowanie i przestaje się bawić"],
      x: "Pytanie otwarte uruchamia projekcję: myśli misia to tak naprawdę myśli dziecka.",
      w: ["Nie chodzi o naukę opisu, tylko o dostęp do przeżyć dziecka.",
          "W pracy twórczej nie ma oceniania.",
          "Pytanie otwarte zwykle wciąga dziecko w rozmowę."] },
    { u: "z1", t: "tf", s: "D",
      q: "Na teście projekcję należy definiować jak w psychoanalizie: jako mechanizm obronny przypisywania innym nieakceptowanych impulsów.",
      a: false,
      x: "Na teście trzymaj się definicji z wykładu: przypisywanie obiektowi zewnętrznemu własnych stanów wewnętrznych, bez założenia obrony." },
    { u: "z1", t: "mcq",
      q: "Jak nazywa się paradygmat związany z zasadą 1?",
      a: ["„Tu i teraz”", "„Krok po kroku”", "„Liczy się wynik”", "„Zero tolerancji”"],
      x: "Zasada 1 to paradygmat „tu i teraz”: ważne jest to, co dzieje się w trakcie tworzenia.",
      w: ["To hasło sztywnej instrukcji, a nie pracy twórczej.",
          "To dokładnie przeciwieństwo zasady 1.",
          "To hasło dyscypliny, sprzeczne z klimatem bez oceniania."] },
    { u: "z1", t: "tf", q: "Dobrą praktyką jest chwalenie estetyki dzieła, np. „super”, żeby zmotywować dziecko.", a: false,
      x: "Psycholog nie ocenia estetyki. Zamiast „piękny rysunek” czy „super” opisuje, co widzi, i zaprasza do opowiedzenia." },

    /* ---------- Zielony ołówek ---------- */
    { u: "z2", t: "mcq",
      q: "Na czym polega zasada zielonego ołówka?",
      a: ["Zauważa się i wzmacnia to, co unikalne i ciekawe (zasoby), zamiast wytykać błędy",
          "Błędy poprawia się na zielono, żeby mniej raziły dziecko i rodziców", "Ocenia się tylko te prace, które dziecko wykonało zielonym kolorem",
          "Nagradza się zielonym ołówkiem najlepszą pracę w całej grupie"],
      x: "Zielony ołówek zaznacza to, co dobre i ciekawe, czyli zasoby. Czerwony wytykałby błędy, a tego psycholog unika.",
      w: ["To nadal wytykanie błędów, tylko innym kolorem.",
          "Kolor pracy nie ma tu znaczenia, to metafora.",
          "Nagradzanie najlepszych to rywalizacja, a nie wzmacnianie zasobów każdego."] },
    { u: "z2", t: "type", q: "Jakie hasło było wyróżnione na slajdzie przy zasadzie zielonego ołówka?", a: ["zasoby"],
      x: "ZASOBY: patrzymy na to, co dziecko ma i co mu wychodzi, a nie na błędy." },
    { u: "z2", t: "mcq",
      q: "Co w tej metaforze oznacza czerwony ołówek?",
      a: ["Wytykanie błędów i tego, co „nie wyszło”", "Wzmacnianie zasobów i ciekawych pomysłów", "Prawo uczestnika do odmowy",
          "Wyrażanie złości w pracy twórczej"],
      x: "Czerwony ołówek, jak w szkole, zaznacza błędy. Psycholog go odkłada.",
      w: ["To zielony ołówek.",
          "Prawo do odmowy to osobny element zasady 2.",
          "Złość to temat zasady 10, a nie metafory ołówków."] },
    { u: "z2", t: "tf", q: "Uczestnik zawsze może powiedzieć „NIE” i nie pokazywać swojej pracy grupie.", a: true,
      x: "To prawo do odmowy." },
    { u: "z2", t: "mcq",
      q: "Kiedy uczestnik może nie pokazywać pracy grupie?",
      a: ["Zawsze, także wtedy, gdy po prostu nie chce", "Tylko wtedy, gdy praca dotyczy traumy", "Tylko za pisemną zgodą rodziców",
          "Nigdy, dzielenie się jest obowiązkowe"],
      x: "Prawo do odmowy: uczestnik zawsze może powiedzieć „NIE”. Nie musi się tłumaczyć.",
      w: ["Nie tylko przy traumie: wystarczy, że nie chce.",
          "Zgoda rodziców nie jest potrzebna, decyduje uczestnik.",
          "Obowiązek łamałby prawo do odmowy."] },
    { u: "z2", t: "mcq",
      q: "Dlaczego twórczość wiąże się z ryzykiem emocjonalnym?",
      a: ["Bo wymaga odsłonięcia się", "Bo materiały bywają niebezpieczne", "Bo zajęcia są zawsze oceniane", "Bo zajęcia trwają zbyt długo"],
      x: "Tworząc, pokazujesz coś z siebie. To odsłonięcie, a więc ryzyko, zwłaszcza u młodzieży. Dlatego potrzebne jest bezpieczeństwo.",
      w: ["Chodzi o ryzyko emocjonalne, a nie fizyczne.",
          "Właśnie nie: oceny są zawieszone.",
          "Czas trwania nie ma tu znaczenia."] },
    { u: "z2", t: "cloze", q: "Specyfika tych zajęć to całkowite zawieszenie krytyki i ___ szkolnych.",
      a: ["ocen", "zasad", "przerw", "lekcji"],
      x: "Całkowite zawieszenie krytyki i ocen szkolnych: to warunek psychologicznego bezpieczeństwa.",
      w: ["Zasady zostają, np. setting i prawo do odmowy.",
          "Przerwy nie mają tu znaczenia.",
          "Nie zawieszamy lekcji, tylko ocenianie."] },
    { u: "z2", t: "mcq", s: "U",
      q: "Skoro „nie da się uciec od oceniania”, co według prowadzącej robi psycholog?",
      a: ["Świadomie zmienia kierunek oceny: na zasoby, nie na błędy", "Ukrywa swoje oceny, żeby dziecko ich nie widziało",
          "Ocenia wyłącznie efekt końcowy, a nie proces", "Przekazuje ocenianie grupie rówieśników"],
      x: "Ocena zawsze gdzieś się pojawia, więc psycholog kieruje ją na zasoby: co się udaje, co jest ciekawe.",
      w: ["Ukrywanie to nadal ocenianie błędów, tylko po cichu.",
          "To sprzeczne z zasadą 1 (proces ważniejszy niż efekt).",
          "Ocena rówieśników to dla młodzieży największy lęk."] },
    { u: "z2", t: "tf", q: "Ryzyko emocjonalne związane z odsłonięciem się jest szczególnie duże u młodzieży.", a: true,
      x: "Tak. Młodzież najbardziej boi się oceny rówieśników, więc odsłonięcie się kosztuje ją najwięcej." },
    { u: "z2", t: "mcq", s: "D",
      q: "Z jakim nurtem polskiej dydaktyki kojarzy się „zielony ołówek”?",
      a: ["Z ocenianiem kształtującym", "Z pedagogiką Montessori", "Z behawioryzmem szkolnym", "Z edukacją zdalną"],
      x: "„Zielony ołówek” to znane narzędzie oceniania kształtującego: zaznacza się to, co dobre, zamiast samych błędów.",
      w: ["Montessori to inna pedagogika, oparta na samodzielnej pracy z materiałami.",
          "Behawioryzm opiera się na nagrodach i karach.",
          "Edukacja zdalna to forma nauki, a nie nurt oceniania."] },
    { u: "z2", t: "mcq",
      q: "Jak brzmi pełna nazwa zasady 2?",
      a: ["Zasada psychologicznego bezpieczeństwa (klimat bez oceniania)", "Zasada pozytywnej dyscypliny (jasne kary i nagrody)",
          "Zasada równego traktowania (te same zadania dla wszystkich)", "Zasada aktywnego słuchania (prowadzący głównie słucha)"],
      x: "Zasada 2: psychologiczne bezpieczeństwo, czyli klimat bez oceniania. Należą do niej zielony ołówek i prawo do odmowy.",
      w: ["Dyscypliny nie ma wśród 10 zasad.",
          "Równe traktowanie nie jest nazwą żadnej z zasad.",
          "Aktywne słuchanie nie jest nazwą zasady z wykładu."] },

    /* ---------- Zmysły i zwroty akcji ---------- */
    { u: "z34", t: "mcq",
      q: "Aktywacja polisensoryczna to…",
      a: ["angażowanie wielu zmysłów naraz", "nauka wyłącznie przez myślenie pojęciowe", "praca jednym materiałem przez całe zajęcia",
          "relaksacja z zamkniętymi oczami"],
      x: "Poli znaczy wiele, sensoryczny to zmysłowy. Wiele zmysłów naraz: dotyk, słuch, węch, wzrok.",
      w: ["To przeciwieństwo: zasada 3 ma odciągnąć od samego myślenia pojęciowego.",
          "Jeden materiał to raczej jeden zmysł.",
          "Zamknięte oczy wyłączają zmysł, a nie angażują więcej."] },
    { u: "z34", t: "mcq",
      q: "Dlaczego dzieci i młodzież potrzebują aktywacji polisensorycznej?",
      a: ["W dobie przebodźcowania cyfrowego potrzebują zakotwiczenia w ciele", "Bo w tym wieku nie potrafią jeszcze w ogóle myśleć pojęciowo",
          "Bo szkoła zabrania im ruchu, więc muszą to nadrobić na zajęciach", "Bo dzięki pracy wieloma zmysłami zajęcia trwają krócej"],
      x: "Slajd: w dobie przebodźcowania cyfrowego dzieci i młodzież potrzebują zakotwiczenia w ciele.",
      w: ["Potrafią, ale samo myślenie pojęciowe nie wystarcza.",
          "Wykład nie mówi o zakazie ruchu w szkole.",
          "Długość zajęć nie ma tu znaczenia."] },
    { u: "z34", t: "mcq",
      q: "Który przykład ilustruje aktywację polisensoryczną?",
      a: ["Glina przy muzyce, malowanie na podłodze, zapachy i faktury", "Rozwiązywanie testu przy biurku w ciszy",
          "Samodzielne czytanie podręcznika przez godzinę", "Słuchanie wykładu z prezentacją na ekranie"],
      x: "Glina (dotyk), muzyka (słuch), zapachy (węch), faktury (dotyk): wiele zmysłów naraz.",
      w: ["Test przy biurku to praca na samym myśleniu pojęciowym.",
          "Czytanie angażuje głównie wzrok i myślenie.",
          "Wykład to głównie słuch i wzrok, bez ciała."] },
    { u: "z34", t: "mcq",
      q: "Jaki efekt daje aktywacja polisensoryczna?",
      a: ["Reguluje układ nerwowy i ułatwia ekspresję osobom, którym trudno mówić o emocjach",
          "Poprawia oceny z plastyki i technikę rysunku u większości dzieci", "Skraca czas zajęć, bo dzieci szybciej kończą zadania twórcze",
          "Zastępuje rozmowę z psychologiem, więc rozmowa nie jest potrzebna"],
      x: "Slajd: aktywacja wielu zmysłów reguluje układ nerwowy i ułatwia ekspresję tym, którym trudno mówić o emocjach.",
      w: ["Oceny są zawieszone, a celem nie jest technika.",
          "Czas zajęć nie jest celem.",
          "Zmysły ułatwiają ekspresję, ale nie zastępują psychologa."] },
    { u: "z34", t: "type", s: "D", q: "Najbardziej znana realizacja środowisk wielozmysłowych, sala doświadczania świata z Holandii, to…",
      a: ["snoezelen"],
      x: "Snoezelen: sala z Holandii, w której światło, dźwięk, zapach i dotyk są celowo zaaranżowane." },
    { u: "z34", t: "tf", s: "U", q: "Samo siedzenie przy biurku to praca wyłącznie na myśleniu pojęciowym, której zasada 3 ma zapobiegać.", a: true,
      x: "Tak. Zasada 3 każe wyjść poza biurko i angażować ciało oraz zmysły." },
    { u: "z34", t: "mcq",
      q: "Co jest „największym wrogiem kreatywności” według zasady 4?",
      a: ["Sztywny scenariusz zajęć", "Hałas w sali zajęć", "Brak materiałów plastycznych", "Zbyt duża grupa uczestników"],
      x: "Slajd: sztywny scenariusz to największy wróg kreatywności. Prowadzący musi być gotowy na zwroty akcji.",
      w: ["O hałasie wykład nie mówił.",
          "Brak materiałów utrudnia, ale slajd mówi o sztywnym scenariuszu.",
          "Wielkość grupy nie była na slajdzie."] },
    { u: "z34", t: "type", q: "Hasło wyróżnione na slajdzie przy zasadzie 4: prowadzący musi być gotowy na ZWROTY ______.", a: ["akcji"],
      x: "ZWROTY AKCJI: plan może się zmienić w każdej chwili, jeśli tego potrzebuje grupa." },
    { u: "z34", t: "mcq",
      q: "Zaplanowałeś rysowanie bajki o lęku, a grupa wchodzi poruszona konfliktem w klasie. Co robisz?",
      a: ["Porzucasz plan i przekształcasz metodę w narzędzie do przepracowania kryzysu",
          "Realizujesz scenariusz, bo jest zaplanowany, a konflikt omówicie innym razem",
          "Odwołujesz zajęcia i odsyłasz grupę do wychowawcy, żeby się uspokoiła",
          "Prosisz grupę, żeby zostawiła konflikt za drzwiami i skupiła się na bajce"],
      x: "To przykład ze slajdu: porzucasz plan, a twórczość staje się wentylem bezpieczeństwa dla bieżącego kryzysu (zasada 4).",
      w: ["Sztywny scenariusz to największy wróg kreatywności.",
          "Twórczość może pomóc przepracować konflikt tu i teraz.",
          "Udawanie, że konfliktu nie ma, blokuje proces."] },
    { u: "z34", t: "cloze", q: "W sytuacji kryzysu twórczość staje się ___ bezpieczeństwa.",
      a: ["wentylem", "pasem", "alarmem", "strażnikiem"],
      x: "Wentyl bezpieczeństwa: wypuszcza napięcie w bezpieczny sposób.",
      w: ["Pas trzyma w miejscu, a tu chodzi o ujście napięcia.",
          "Alarm ostrzega, a twórczość pozwala napięcie rozładować.",
          "Strażnik pilnuje, a tu chodzi o ujście emocji."] },
    { u: "z34", t: "tf", s: "U", q: "Scenariusz warsztatów jest obowiązkiem do wykonania, a nie punktem wyjścia.", a: false,
      x: "Odwrotnie: scenariusz to punkt wyjścia, a nie obowiązek. Dotyczy to każdych warsztatów." },
    { u: "z34", t: "mcq",
      q: "Jaką metodę wymienia slajd przy zasadzie 3?",
      a: ["Multi-sensory environments", "Mind mapping (mapy myśli)", "Burza mózgów w małych grupach", "Metoda projektów edukacyjnych"],
      x: "Multi-sensory environments, czyli środowiska wielozmysłowe. Najbardziej znany przykład to Snoezelen.",
      w: ["Mapa myśli to technika pojęciowa, a nie zmysłowa.",
          "Burza mózgów to technika myślenia grupowego.",
          "Metoda projektów to metoda dydaktyczna."] },

    /* ---------- Metafora i setting ---------- */
    { u: "z56", t: "mcq",
      q: "Dlaczego metody twórcze sięgają po narzędzia projekcyjne (zasada 5)?",
      a: ["Bo dzieciom i młodzieży trudno mówić wprost o lękach, kompleksach i traumach",
          "Bo narzędzia projekcyjne są tańsze i szybsze od zwykłej rozmowy", "Bo pozwalają szybko i trafnie postawić diagnozę psychologiczną",
          "Bo dzieci z zasady nie lubią rozmawiać z dorosłymi o czymkolwiek"],
      x: "Wprost o lękach mówić trudno. Przez metaforę, bajkę czy rolę jest łatwiej, bo jest bezpieczny dystans.",
      w: ["Koszt nie jest powodem, powodem jest trudność mówienia wprost.",
          "Celem nie jest diagnoza, tylko bezpieczna ekspresja.",
          "Nie chodzi o niechęć do dorosłych, tylko o trudne tematy."] },
    { u: "z56", t: "mcq",
      q: "Który przykład z wykładu ilustruje bajkoterapię?",
      a: ["Opowieść o „smutnym potworze, który zgubił się w lesie”", "Granie zbuntowanego bohatera przed całą grupą",
          "Rundka „jakim kolorem dziś jesteś?” na początek", "Uderzanie w ciężką glinę, żeby wyładować złość"],
      x: "Bajka o smutnym potworze to bajkoterapia: o swoim smutku łatwiej mówić przez postać.",
      w: ["Granie roli to drama.",
          "Rundka to rytuał rozpoczęcia (zasada 6).",
          "Glina do uderzania to kanalizacja (zasada 10)."] },
    { u: "z56", t: "mcq", q: "Zagranie zbuntowanego bohatera to przykład…",
      a: ["dramy", "bajkoterapii", "kolażu", "art journalingu"],
      x: "Odgrywanie roli to drama. Tak jak bajka, daje bezpieczny dystans (zasada 5).",
      w: ["Bajkoterapia to opowieść, a nie odgrywanie roli.",
          "Kolaż to praca z wycinkami i zdjęciami.",
          "Art journaling to twórczy dziennik."] },
    { u: "z56", t: "cloze", q: "Metafora i symbolika dają dziecku ___.",
      a: ["bezpieczeństwo", "ocenę", "nagrodę", "diagnozę"],
      x: "Slajd: metafora i symbolika dają bezpieczeństwo, bo można mówić o sobie, nie mówiąc wprost.",
      w: ["Oceny w pracy twórczej nie ma.",
          "Nie chodzi o nagrodę, tylko o bezpieczny dystans.",
          "Celem nie jest diagnoza."] },
    { u: "z56", t: "mcq",
      q: "Jaki dystans zapewnia metaforyzacja?",
      a: ["Bezpieczny dystans emocjonalny", "Dystans fizyczny od prowadzącego", "Dystans od grupy rówieśniczej", "Dystans czasowy od zdarzenia"],
      x: "Metafora daje bezpieczny dystans emocjonalny: mówię o potworze, a nie wprost o sobie.",
      w: ["Nie chodzi o odległość w sali.",
          "Grupa zostaje, dystans dotyczy emocji.",
          "Zdarzenie może być bieżące, dystans jest emocjonalny."] },
    { u: "z56", t: "type", q: "Jakie hasło wyróżniono na slajdzie przy zasadzie 6 (rytualizacja)?", a: ["setting"],
      x: "SETTING: jasne ramy i rytuały, które oddzielają zajęcia od „zwykłej rzeczywistości”." },
    { u: "z56", t: "mcq",
      q: "Czym jest setting?",
      a: ["Granicami i rytuałami, które oddzielają zajęcia od „zwykłej rzeczywistości”",
          "Dekoracją sali, którą prowadzący przygotowuje przed każdymi zajęciami",
          "Planem zajęć na cały semestr, rozpisanym dokładnie tydzień po tygodniu",
          "Ustawieniem oświetlenia i muzyki tak, żeby wszystkim było przyjemnie"],
      x: "Setting to ramy: rytuały rozpoczęcia i zakończenia oraz zmiana przestrzeni, które oddzielają zajęcia od codzienności.",
      w: ["Dekoracja może być częścią przestrzeni, ale setting to przede wszystkim granice i rytuały.",
          "Plan semestru to organizacja kursu, a nie ramy spotkania.",
          "Światło i muzyka to raczej zmysły (zasada 3)."] },
    { u: "z56", t: "mcq",
      q: "Który przykład wykład podaje jako rytuał rozpoczęcia?",
      a: ["Iskierka przyjaźni albo rundka „jakim kolorem dziś jesteś?”", "Sprawdzenie listy obecności na samym początku zajęć",
          "Kartkówka na wejście z materiału z poprzednich zajęć", "Rozdanie ocen za prace wykonane na poprzednich zajęciach"],
      x: "Iskierka przyjaźni i rundka „jakim kolorem dziś jesteś?” to rytuały rozpoczęcia z wykładu.",
      w: ["Lista obecności to szkolna formalność, a nie rytuał twórczy.",
          "Kartkówka to ocenianie, a oceny są zawieszone.",
          "Oceny są zawieszone (zasada 2)."] },
    { u: "z56", t: "tf", q: "Odsunięcie ławek i siadanie w kręgu na poduszkach to element ram przestrzennych zajęć.", a: true,
      x: "Fizyczna zmiana przestrzeni oddziela zajęcia twórcze od zwykłej lekcji." },
    { u: "z56", t: "mcq", s: "D",
      q: "Iskierka przyjaźni to…",
      a: ["zabawa w kręgu, w której uczestnicy kolejno przekazują sobie uścisk dłoni", "wspólne rysowanie ogniska na dużym arkuszu papieru",
          "zabawa z latarką w zaciemnionej sali, w której szuka się przedmiotów", "pochwała dla najlepszego uczestnika na koniec zajęć"],
      x: "Iskierka przyjaźni: siedzicie w kręgu i „puszczacie iskierkę”, czyli uścisk dłoni, od osoby do osoby.",
      w: ["Nazwa kojarzy się z ogniem, ale to zabawa z uściskiem dłoni.",
          "Nie ma w niej latarki, jest uścisk dłoni w kręgu.",
          "Wyróżnianie najlepszych to rywalizacja, sprzeczna z zasadą 2."] },
    { u: "z56", t: "mcq",
      q: "Po co są rytuały rozpoczęcia i zakończenia zajęć?",
      a: ["Wyznaczają granice między przestrzenią twórczą a „zwykłą rzeczywistością”", "Wydłużają zajęcia, żeby grupa miała więcej czasu na pracę",
          "Pozwalają szybko sprawdzić obecność wszystkich uczestników", "Pomagają ocenić zaangażowanie każdego uczestnika"],
      x: "Rytuały to setting: wyraźny początek i koniec oddzielają bezpieczną przestrzeń twórczą od codzienności.",
      w: ["Długość zajęć nie jest celem rytuałów.",
          "Obecność to formalność, a rytuał ma budować ramy.",
          "Oceny są zawieszone."] },
    { u: "z56", t: "tf",
      q: "Według wykładu dziecku łatwiej powiedzieć „czuję się samotny i nierozumiany przez rodziców” niż opowiedzieć o smutnym potworze.",
      a: false,
      x: "Odwrotnie. Metafora daje bezpieczny dystans, dlatego łatwiej mówić o potworze niż o sobie." },
    { u: "z56", t: "mcq", s: "D",
      q: "W psychoterapii „setting” oznacza…",
      a: ["stałe ramy spotkań: miejsce, czas i zasady", "diagnozę wstępną przed rozpoczęciem terapii", "ćwiczenia relaksacyjne na początku sesji",
          "superwizję pracy terapeuty przez kolegę"],
      x: "W psychoterapii setting to stałe ramy: to samo miejsce, czas i zasady spotkań.",
      w: ["Diagnoza to osobny etap, a nie ramy spotkań.",
          "Relaksacja może być elementem sesji, ale setting to ramy.",
          "Superwizja to wsparcie terapeuty, a nie ramy spotkań z klientem."] },

    /* ---------- Opór ---------- */
    { u: "z7", t: "mcq",
      q: "Co niemal zawsze kryje się za tekstami „to jest dla dzieci” albo „nie umiem rysować”?",
      a: ["Lęk przed oceną, odrzuceniem przez grupę lub trudnymi emocjami", "Zwykłe lenistwo i brak chęci do jakiejkolwiek pracy",
          "Brak talentu plastycznego, który uczestnik dobrze zna", "Chęć zwrócenia na siebie uwagi całej grupy"],
      x: "Slajd: pod oporem kryje się lęk przed oceną, przed odrzuceniem przez grupę albo przed dotknięciem trudnych emocji.",
      w: ["Wykład nie traktuje oporu jako lenistwa, tylko jako lęk.",
          "Talent nie ma znaczenia, liczy się proces.",
          "Opór to raczej ochrona przed oceną niż szukanie uwagi."] },
    { u: "z7", t: "mcq",
      q: "Jak psycholog reaguje na opór?",
      a: ["Nie walczy i nie zmusza, przyjmuje opór z empatią", "Stawia uwagę i informuje o wszystkim wychowawcę",
          "Przekonuje argumentami, że naprawdę warto spróbować", "Ignoruje uczestnika aż do samego końca zajęć"],
      x: "Opór jest naturalny, a pod nim jest lęk. Walka go wzmacnia, empatia go rozpuszcza.",
      w: ["Kara wzmacnia lęk przed oceną.",
          "Przekonywanie to nadal nacisk, a psycholog nie naciska.",
          "Ignorowanie to odrzucenie, a tego uczestnik się boi."] },
    { u: "z7", t: "mcq",
      q: "Którą reakcję na opór wykład podaje jako właściwą?",
      a: ["„Masz prawo uważać to zadanie za nudne. Możesz po prostu posiedzieć z nami i popatrzeć.”",
          "„Wszyscy robią, więc ty też musisz. Inaczej nie zaliczysz dzisiejszych zajęć.”",
          "„Nie przesadzaj, to nic trudnego. Każdy sobie z tym radzi, ty też dasz radę.”",
          "„Jak nie chcesz, to wyjdź i nie przeszkadzaj reszcie grupy, która chce pracować.”"],
      x: "Uznanie prawa do oporu i zaproszenie bez nacisku. Często po kilkunastu minutach uczestnik sam dołącza.",
      w: ["To przymus, który wzmacnia opór.",
          "Bagatelizowanie lęku to brak empatii.",
          "Wyrzucenie to odrzucenie, a tego uczestnik się boi."] },
    { u: "z7", t: "tf", q: "U dzieci, a zwłaszcza u młodzieży, opór jest naturalnym elementem procesu.", a: true,
      x: "Tak, to sedno zasady 7. U dorosłych opór jest rzadszy, u młodzieży naturalny." },
    { u: "z7", t: "tf", q: "U dorosłych opór w ogóle nie występuje, bo przychodzą dobrowolnie.", a: false,
      x: "Pojawia się rzadko, ale może być zakamuflowany i subtelny." },
    { u: "z7", t: "mcq",
      q: "Co często robi młodzież, gdy nie czuje nacisku?",
      a: ["Po kilkunastu minutach sama dołącza", "Wychodzi z zajęć przed końcem", "Zaczyna przeszkadzać innym", "Prosi prowadzącego o ocenę"],
      x: "Wykład: bez nacisku młodzież często po kilkunastu minutach sama dołącza do zajęć.",
      w: ["Brak nacisku zmniejsza potrzebę ucieczki.",
          "Przeszkadzanie to raczej reakcja na nacisk.",
          "Ocen nie ma, a młodzież boi się oceny."] },
    { u: "z7", t: "mcq", s: "U",
      q: "Z którą zasadą prowadząca połączyła prawo uczestnika do oporu?",
      a: ["Z prawem do odmowy (zasada 2)", "Z aktywacją polisensoryczną (zasada 3)", "Z kanalizacją i sublimacją (zasada 10)",
          "Z teorią umysłu i perspektywą (zasada 8)"],
      x: "Prawo do oporu łączy się z prawem do odmowy: uczestnik może powiedzieć „nie” i to jest w porządku.",
      w: ["Zasada 3 dotyczy zmysłów.",
          "Zasada 10 dotyczy kierowania napięcia.",
          "Zasada 8 dotyczy cudzej perspektywy."] },
    { u: "z7", t: "cloze", q: "Zasada 7 to ___ oporu.",
      a: ["ambiwalencja", "eliminacja", "przełamywanie", "kara"],
      x: "Ambiwalencja to dwoistość: uczestnik jednocześnie chce i nie chce. Opór jest naturalny i ma swoje powody.",
      w: ["Nie eliminujemy oporu, przyjmujemy go.",
          "Nie przełamujemy oporu siłą.",
          "Kara wzmacnia lęk, który jest pod oporem."] },
    { u: "z7", t: "mcq",
      q: "Jak wykład opisuje opór u dorosłych?",
      a: ["Pojawia się rzadko, ale bywa zakamuflowany i subtelny", "Jest głośny, otwarty i łatwy do zauważenia",
          "Zawsze świadczy o jakimś zaburzeniu", "Występuje częściej i mocniej niż u dzieci"],
      x: "U dorosłych opór jest rzadki, ale może być ukryty i subtelny.",
      w: ["Raczej odwrotnie: u dorosłych bywa zakamuflowany.",
          "Opór to naturalny element procesu, a nie objaw.",
          "Częstszy jest u dzieci, a zwłaszcza u młodzieży."] },
    { u: "z7", t: "tf", s: "U", q: "Nie każde zadanie spodoba się każdemu uczestnikowi i uczestnik ma prawo do oporu.", a: true,
      x: "Tak powiedziała prowadząca: opór jest normalny i uczestnik ma do niego prawo (łączy się to z prawem do odmowy)." },

    /* ---------- Cudza perspektywa ---------- */
    { u: "z8", t: "mcq",
      q: "Dlaczego grupowa praca twórcza (drama, wspólne pisanie scenariusza) to potężne narzędzie?",
      a: ["To trening społeczny, który wymusza przyjęcie cudzej perspektywy", "Pozwala szybko wyłonić naturalnego lidera grupy",
          "Jest szybsza i wygodniejsza od pracy indywidualnej", "Ułatwia prowadzącemu ocenianie uczestników"],
      x: "Wspólne tworzenie zmusza do zobaczenia sytuacji oczami innych. To trening wychodzenia z egocentryzmu (zasada 8).",
      w: ["Wyłanianie lidera nie jest celem zasady 8.",
          "Tempo nie jest celem.",
          "Oceny są zawieszone."] },
    { u: "z8", t: "mcq",
      q: "W jakim egocentryzmie naturalnie tkwią młodsze dzieci?",
      a: ["Poznawczym", "Adolescentnym", "Społecznym", "Narcystycznym"],
      x: "Młodsze dzieci tkwią w egocentryzmie poznawczym: nie odróżniają swojej wiedzy od wiedzy innych (Piaget).",
      w: ["Adolescentny dotyczy młodzieży.",
          "Takiej nazwy nie było na slajdzie.",
          "Narcyzm to inna kategoria, nie etap rozwoju."] },
    { u: "z8", t: "mcq",
      q: "Jak slajd nazywa silne skupienie młodzieży na własnym przeżywaniu?",
      a: ["Egocentryzm adolescentny", "Egocentryzm poznawczy", "Egocentryzm percepcyjny", "Egoizm rozwojowy"],
      x: "Egocentryzm adolescentny (Elkind): wyobrażona publiczność i baśń osobista.",
      w: ["Poznawczy dotyczy młodszych dzieci.",
          "Percepcyjny to „inni widzą to co ja”, a slajd mówi o adolescentnym.",
          "Takiej nazwy nie było na slajdzie."] },
    { u: "z8", t: "mcq",
      q: "Które zadanie wymusza przyjęcie perspektywy innej osoby lub obiektu?",
      a: ["„Napisz list z perspektywy twojego nauczyciela”", "„Narysuj swój dom i opowiedz, kto w nim mieszka”",
          "„Opowiedz, co robiłeś w ostatni weekend”", "„Ulep dowolną figurkę z gliny”"],
      x: "List z perspektywy nauczyciela każe pomyśleć, jak on widzi świat. To przykład z wykładu do zasady 8.",
      w: ["To nadal twoja perspektywa.",
          "To opowieść o sobie.",
          "Dowolna figurka nie wymaga cudzej perspektywy."] },
    { u: "z8", t: "mcq", s: "U",
      q: "Dziecko w zabawie zakłada, że obowiązują zasady, które samo wymyśliło i nikomu nie powiedziało. To egocentryzm…",
      a: ["poznawczy", "adolescentny", "afektywny", "percepcyjny"],
      x: "Dziecko nie odróżnia swojej wiedzy od wiedzy innych, a to egocentryzm poznawczy." },
    { u: "z8", t: "mcq", s: "U",
      q: "„Idę na imprezę z pryszczem, to wina świata, więc obrażam się na wszystkich”. Jak prowadząca nazwała ustnie ten egocentryzm?",
      a: ["Afektywny (emocjonalny)", "Poznawczy (umysłowy)", "Percepcyjny (wzrokowy)", "Przedoperacyjny (dziecięcy)"],
      x: "Ustnie padła nazwa „egocentryzm afektywny”. Na slajdzie skupienie młodzieży na własnym przeżywaniu to egocentryzm adolescentny i tej nazwy używaj na teście.",
      w: ["Poznawczy to nieodróżnianie swojej wiedzy od cudzej (np. zasady zabawy).",
          "Percepcyjny to „inni widzą to co ja”.",
          "Przedoperacyjne to stadium u Piageta, a nie rodzaj egocentryzmu."] },
    { u: "z8", t: "type", s: "D", q: "Zdolność przypisywania innym stanów psychicznych (przekonań, intencji) odmiennych od własnych to teoria…",
      a: ["umysłu"],
      x: "Teoria umysłu: rozumiem, że inni mają w głowie coś innego niż ja. To przeciwieństwo egocentryzmu." },
    { u: "z8", t: "mcq", s: "D",
      q: "Kto opisał egocentryzm poznawczy jako cechę stadium przedoperacyjnego?",
      a: ["J. Piaget", "D. Elkind", "J. Rotter", "C. Rogers"],
      x: "Jean Piaget: w stadium przedoperacyjnym (ok. 2–7 lat) dziecko myśli egocentrycznie.",
      w: ["Elkind opisał egocentryzm adolescentny.",
          "Rotter to umiejscowienie kontroli.",
          "Rogers to facylitacja i nurt humanistyczny."] },
    { u: "z8", t: "mcq", s: "D", q: "Kto opisał egocentryzm adolescentny?",
      a: ["D. Elkind", "J. Piaget", "Z. Freud", "J. Huizinga"],
      x: "David Elkind: wyobrażona publiczność i baśń osobista to jego pojęcia.",
      w: ["Piaget opisał egocentryzm poznawczy dzieci.",
          "Freud to sublimacja i mechanizmy obronne.",
          "Huizinga to homo ludens."] },
    { u: "z8", t: "match", s: "D",
      pairs: [
        ["Wyobrażona publiczność", "wszyscy mnie obserwują"],
        ["Baśń osobista", "jestem wyjątkowy"],
        ["Egocentryzm poznawczy", "inni wiedzą co innego niż ja"],
        ["Egocentryzm percepcyjny", "inni widzą co innego niż ja"],
        ["Egocentryzm afektywny", "inni czują co innego niż ja"]],
      x: "Publiczność: „wszyscy mnie obserwują”. Baśń osobista: „jestem wyjątkowy”. Poznawczy, percepcyjny i afektywny różnią się tym, czego dotyczy: wiedzy, widzenia czy uczuć." },
    { u: "z8", t: "tf", s: "D",
      q: "Na teście skupienie młodzieży na własnym przeżywaniu (np. przykład z pryszczem) nazywaj egocentryzmem adolescentnym, tak jak na slajdzie.",
      a: true,
      x: "Tak. Ustnie padło „afektywny”, ale na slajdzie jest „egocentryzm adolescentny”, a test bazuje na slajdach." },
    { u: "z8", t: "mcq", s: "U",
      q: "Na jakim mechanizmie według prowadzącej budują się duże marki, np. kosmetyczne?",
      a: ["Tworzą warunki, w których odbiorca projektuje na siebie przeżycie", "Na systematycznym obniżaniu cen, żeby przyciągnąć klientów",
          "Na ocenianiu klientów i porównywaniu ich z innymi", "Na sztywnym scenariuszu, który powtarza każda reklama"],
      x: "Marka nie sprzedaje kremu, tylko przeżycie: aranżuje warunki, w których projektujesz na siebie efekt. To ten sam mechanizm projekcji co w pracy twórczej.",
      w: ["O cenach wykład nie mówił.",
          "Ocenianie klientów nie było przykładem z wykładu.",
          "Chodziło o mechanizm projekcji, a nie o formę reklamy."] },
    { u: "z8", t: "mcq", s: "D",
      q: "Czym projekcja w pracy twórczej różni się od marketingu doświadczeń?",
      a: ["Celem: w psychologii to wgląd i rozwój, w marketingu sprzedaż", "Mechanizmem, bo działają na zupełnie innej zasadzie",
          "Tylko liczbą zaangażowanych zmysłów", "Niczym, to dokładnie to samo zjawisko"],
      x: "Mechanizm jest ten sam (projekcja), inny jest cel: wgląd w siebie zamiast sprzedaży.",
      w: ["Mechanizm jest wspólny, różni się cel.",
          "Liczba zmysłów nie jest tu różnicą.",
          "Różnią się celem."] },
    { u: "z8", t: "cloze",
      q: "Zadania z cudzą perspektywą budują empatię i elastyczność ___ w bezpiecznych, fikcyjnych warunkach.",
      a: ["poznawczą", "ruchową", "językową", "twórczą"],
      x: "Elastyczność poznawcza: umiejętność patrzenia na sprawy z różnych stron.",
      w: ["Ruch nie jest tu celem.",
          "Nie chodzi o język, tylko o sposób myślenia.",
          "Twórczość jest narzędziem, a celem elastyczność poznawcza."] },

    /* ---------- Czarne słońce ---------- */
    { u: "z9", t: "mcq",
      q: "Dziecko maluje czarne słońce. Którą zasadę realizuje psycholog, akceptując to?",
      a: ["Doświadczenie sprawczości i internalizację poczucia kontroli", "Aktywację polisensoryczną i zakotwiczenie w ciele",
          "Rytualizację i ramy czasowo-przestrzenne", "Elastyczność struktury i zwroty akcji"],
      x: "Decyzja o kolorze należy do dziecka. „Mój wybór, mój świat” buduje sprawczość (zasada 9).",
      w: ["Zasada 3 dotyczy zmysłów, a nie decyzji dziecka.",
          "Zasada 6 dotyczy rytuałów i ram.",
          "Zasada 4 dotyczy zmiany planu zajęć."] },
    { u: "z9", t: "mcq", s: "U",
      q: "Jak na czarne słońce reaguje nauczyciel plastyki, a jak psycholog?",
      a: ["Nauczyciel poprawi, psycholog zastanowi się, dlaczego dziecko tak namalowało",
          "Obaj poprawią, bo słońce na rysunku dziecka powinno być żółte jak w naturze",
          "Psycholog poprawi, a nauczyciel plastyki zaakceptuje to jako ekspresję",
          "Obaj pochwalą estetykę i oryginalność rysunku, żeby zmotywować dziecko"],
      x: "Ustnie z wykładu: nauczyciel poprawi, psycholog się zastanowi. Kolor może nieść informację o przeżyciach.",
      w: ["Psycholog nie poprawia, to decyzja dziecka.",
          "Jest odwrotnie.",
          "Psycholog nie ocenia estetyki."] },
    { u: "z9", t: "type", q: "Zasada 9: doświadczenie sprawczości i internalizacja poczucia ______ (LOC).", a: ["kontroli"],
      x: "LOC to locus of control, czyli umiejscowienie kontroli. Internalizacja: od „decydują za mnie” do „to zależy ode mnie”." },
    { u: "z9", t: "mcq",
      q: "Wielu młodych ludzi z trudnościami czuje, że nie ma wpływu na swoje życie. Jakie mają umiejscowienie kontroli?",
      a: ["Zewnętrzne", "Wewnętrzne", "Stabilne", "Rozproszone"],
      x: "„Nie mam wpływu” to zewnętrzne umiejscowienie kontroli: wynik zależy od innych albo od losu.",
      w: ["Wewnętrzne to „zależy ode mnie”, czyli odwrotnie.",
          "Takiej kategorii nie ma u Rottera.",
          "Takiej kategorii nie ma u Rottera."] },
    { u: "z9", t: "mcq", s: "D",
      q: "Kto jest autorem koncepcji umiejscowienia kontroli (LOC)?",
      a: ["J. Rotter", "J. Piaget", "G. Vaillant", "K. Sawicka"],
      x: "Julian Rotter: kontrola wewnętrzna (zależy ode mnie) i zewnętrzna (zależy od innych albo od losu).",
      w: ["Piaget to rozwój poznawczy i egocentryzm.",
          "Vaillant to podział mechanizmów obronnych.",
          "Sawicka spopularyzowała socjoterapię w Polsce."] },
    { u: "z9", t: "mcq",
      q: "Co według slajdu daje dziecku „absolutną władzę nad tworzonym światem”?",
      a: ["Czysta kartka, kawałek gliny czy pusta scena", "Gotowy szablon do pokolorowania kredkami",
          "Dokładna instrukcja krok po kroku od nauczyciela", "Pochwała nauczyciela za ładne wykonanie pracy"],
      x: "Pusta kartka czy glina nic nie narzucają, więc każda decyzja należy do dziecka.",
      w: ["Szablon narzuca kształt, więc odbiera decyzje.",
          "Instrukcja decyduje za dziecko.",
          "Pochwała to ocena, a nie władza dziecka nad dziełem."] },
    { u: "z9", t: "cloze", q: "„Ja decyduję, ja kreuję, mój ___ ma znaczenie”.",
      a: ["głos", "wynik", "talent", "rysunek"],
      x: "„Mój głos ma znaczenie”: to zdanie ze slajdu o sprawczości.",
      w: ["Wynik to efekt, a liczy się proces i decyzja.",
          "Talent nie jest tu ważny.",
          "Chodzi o głos dziecka, a nie o sam rysunek."] },
    { u: "z9", t: "tf", q: "Każda decyzja projektowa należy do młodego człowieka. Jeśli trawa w bajce jest niebieska, psycholog to akceptuje.",
      a: true,
      x: "Tak. Niebieska trawa czy czarne słońce to decyzje dziecka i psycholog ich nie poprawia (zasada 9)." },
    { u: "z9", t: "mcq", s: "D",
      q: "Internalizacja poczucia kontroli to…",
      a: ["przesuwanie się od „decydują za mnie” do „to zależy ode mnie”", "przejmowanie kontroli nad całą grupą rówieśników",
          "tłumienie emocji, żeby nad nimi panować", "uzależnienie się od opinii innych ludzi"],
      x: "Internalizacja to uwewnętrznienie: kontrola przesuwa się z zewnątrz („decydują za mnie”) do wewnątrz („zależy ode mnie”).",
      w: ["Nie chodzi o władzę nad innymi, tylko nad własnym życiem.",
          "Tłumienie emocji to nie kontrola w sensie Rottera.",
          "To byłoby zewnętrzne umiejscowienie kontroli."] },
    { u: "z9", t: "mcq", s: "U",
      q: "Przekonanie „ktoś steruje moim losem” odpowiada…",
      a: ["zewnętrznemu umiejscowieniu kontroli", "wewnętrznemu umiejscowieniu kontroli", "sublimacji trudnych emocji",
          "dobrze rozwiniętej teorii umysłu"],
      x: "Los zależy od kogoś innego: to kontrola zewnętrzna.",
      w: ["Wewnętrzne to „zależy ode mnie”.",
          "Sublimacja to zamiana destrukcyjnej energii w wytwór (zasada 10).",
          "Teoria umysłu dotyczy rozumienia cudzych stanów, a nie kontroli."] },
    { u: "z9", t: "mcq", s: "U",
      q: "Co według prowadzącej jest ważne, gdy otoczenie narzuca ramy (grafik w pracy, plan studiów)?",
      a: ["Nie tylko to, jakie ramy są narzucane, ale jak dana osoba je przeżywa", "Żeby ram było jak najwięcej, bo dają poczucie porządku",
          "Żeby ram w ogóle nie było, bo zawsze odbierają kontrolę", "Tylko to, kto je narzuca i jakie ma do tego prawo"],
      x: "Ustnie z wykładu: liczy się też przeżycie ram. Te same ramy jedna osoba przeżywa jako narzucone, a inna jako swój wybór.",
      w: ["Wykład nie zachęcał do mnożenia ram.",
          "Ramy są potrzebne (np. setting), ważne jest ich przeżywanie.",
          "Wykład podkreślał przeżywanie, a nie samo źródło ram."] },
    { u: "z9", t: "tf", s: "U", q: "Wybór koloru jest decyzją dziecka i może nieść informację o jego przeżyciach.", a: true,
      x: "Tak. Dlatego psycholog nie poprawia czarnego słońca, tylko zastanawia się, skąd taki wybór." },

    /* ---------- Glina i bunt ---------- */
    { u: "z10", t: "mcq",
      q: "Czym według nurtu psychodynamicznego jest twórczość?",
      a: ["Najwyższą formą obrony przed lękiem, czyli sublimacją", "Ucieczką od rzeczywistości i od problemów",
          "Objawem zaburzenia, które trzeba leczyć", "Nagrodą za dobre zachowanie na zajęciach"],
      x: "Nurt psychodynamiczny: twórczość to sublimacja, najwyższa (dojrzała) forma obrony przed lękiem.",
      w: ["Sublimacja nie ucieka od problemu, tylko zamienia energię w wytwór.",
          "To dojrzały mechanizm, a nie objaw.",
          "Twórczość nie jest nagrodą, tylko sposobem radzenia sobie z napięciem."] },
    { u: "z10", t: "type", q: "Zamiana destrukcyjnej energii w konstruktywny lub ekspresyjny wytwór to…", a: ["sublimacja"],
      x: "Sublimacja: złość czy napięcie zamieniają się w coś twórczego, np. rzeźbę albo piosenkę." },
    { u: "z10", t: "mcq",
      q: "Nastolatek jest pełen agresji. Co proponuje wykład?",
      a: ["Dać mu ciężką glinę do uderzania albo pozwolić napisać buntowniczy tekst piosenki",
          "Stłumić agresję i od razu wyciągnąć wobec niego poważne konsekwencje",
          "Wysłać go do pedagoga szkolnego, żeby porozmawiał z nim o zachowaniu",
          "Kazać mu się uspokoić i usiąść spokojnie na miejscu do końca zajęć"],
      x: "Kanalizacja: agresja dostaje twórczy kierunek (glina, tekst piosenki), zamiast być tłumiona.",
      w: ["Tłumienie to dokładnie to, czego zasada 10 każe unikać.",
          "Psycholog sam może nadać napięciu kierunek.",
          "Uciszanie wygasza, a nie kieruje napięciem."] },
    { u: "z10", t: "mcq",
      q: "Co zrobić z ruchem nadaktywnego dziecka?",
      a: ["Zamienić go w ekspresyjny taniec lub improwizację ruchową", "Uciszyć dziecko i posadzić je przy stoliku z kartką",
          "Posadzić je w pierwszej ławce, blisko prowadzącego", "Wysłać je na korytarz, żeby się trochę wybiegało"],
      x: "Ruchu nie wygaszamy, tylko nadajemy mu kierunek: taniec, improwizacja (zasada 10).",
      w: ["To wygaszanie, a nie kanalizacja.",
          "To tłumienie ruchu.",
          "Odesłanie nie nadaje energii twórczego kierunku."] },
    { u: "z10", t: "tf", s: "U", q: "Zadaniem psychologa jest wygaszenie nadmiaru napięcia u dziecka.", a: false,
      x: "Nie wygaszenie, lecz nadanie mu kierunku: przekształcenie w twórczą aktywność." },
    { u: "z10", t: "mcq", s: "D", q: "Kto opisał sublimację jako mechanizm obronny?",
      a: ["Z. Freud", "C. Rogers", "J. Rotter", "J. Huizinga"],
      x: "Zygmunt Freud opisał sublimację w psychoanalizie. Vaillant później zaliczył ją do mechanizmów dojrzałych.",
      w: ["Rogers to nurt humanistyczny i facylitacja.",
          "Rotter to umiejscowienie kontroli.",
          "Huizinga to homo ludens, czyli zabawa jako źródło kultury."] },
    { u: "z10", t: "mcq", s: "D",
      q: "Do jakich mechanizmów obronnych sublimację zalicza G. Vaillant?",
      a: ["Dojrzałych", "Niedojrzałych", "Psychotycznych", "Narcystycznych"],
      x: "Vaillant zalicza sublimację do mechanizmów dojrzałych, czyli najzdrowszych sposobów radzenia sobie z lękiem.",
      w: ["Niedojrzałe to np. projekcja w sensie psychoanalitycznym czy acting out.",
          "Psychotyczne to np. zaprzeczanie rzeczywistości.",
          "Takiej grupy u Vaillanta nie ma."] },
    { u: "z10", t: "cloze", q: "Zasada 10: ___ i sublimacja popędów oraz trudnych emocji.",
      a: ["kanalizacja", "eliminacja", "kumulacja", "negacja"],
      x: "Kanalizacja: nadanie napięciu kanału, czyli kierunku.",
      w: ["Nie eliminujemy emocji, tylko je kierujemy.",
          "Kumulacja oznacza gromadzenie napięcia, a tu chodzi o jego ujście.",
          "Negacja to zaprzeczanie, przeciwieństwo pracy z emocjami."] },
    { u: "z10", t: "mcq",
      q: "Jakie trudne stany wymienia slajd przy zasadzie 10?",
      a: ["Napięcie, złość, lęk, energię seksualną", "Nudę, zmęczenie, głód i senność", "Radość, ekscytację, dumę i wdzięczność",
          "Wyłącznie smutek, żal i tęsknotę"],
      x: "Slajd wymienia: napięcie, złość, lęk i energię seksualną. To energie, którym nadaje się twórczy kierunek.",
      w: ["To stany fizjologiczne, a nie te ze slajdu.",
          "To przyjemne emocje, a slajd mówi o trudnych.",
          "Slajd wymienia więcej stanów."] },

    /* ---------- Dzieci a młodzież ---------- */
    { u: "tab", t: "sort", q: "Główny cel pracy twórczej: u kogo?",
      cats: ["Dzieci", "Młodzież"],
      why: ["U dzieci celem są zmysły, ciekawość i przełamywanie schematów poznawczych.",
            "U młodzieży celem są autorefleksja, tożsamość i kanalizowanie trudnych emocji."],
      items: [
        ["rozwój sensoryczny", 0], ["ciekawość", 0], ["przełamywanie schematów poznawczych", 0], ["autorefleksja", 1], ["budowanie tożsamości", 1],
        ["kanalizowanie trudnych emocji", 1]],
      x: "Dzieci: rozwój sensoryczny, ciekawość, przełamywanie schematów. Młodzież: autorefleksja, tożsamość, kanalizowanie emocji." },
    { u: "tab", t: "mcq",
      q: "Jaka jest rola prowadzącego wobec młodzieży?",
      a: ["Partner w dyskusji, świadek procesu, gwarant poufności", "Towarzysz w zabawie i animator dostarczający bodźców",
          "Nauczyciel, który ocenia postępy uczestników", "Ekspert, który wie najlepiej i naprawia problemy"],
      x: "Z tabeli: wobec młodzieży prowadzący to partner w dyskusji, świadek procesu, gwarant poufności i bezpieczeństwa.",
      w: ["To rola wobec dzieci.",
          "Oceniania nie ma.",
          "Ekspert, który naprawia, to przeciwieństwo facylitatora."] },
    { u: "tab", t: "mcq",
      q: "Jaka jest rola prowadzącego wobec dzieci?",
      a: ["Towarzysz w zabawie, facylitator i animator", "Gwarant poufności i bezpieczeństwa całej grupy",
          "Partner w dyskusji o wartościach i tożsamości", "Egzaminator, który sprawdza i ocenia postępy"],
      x: "Z tabeli: wobec dzieci prowadzący to towarzysz w zabawie, facylitator i animator dostarczający bodźców.",
      w: ["To rola wobec młodzieży.",
          "To rola wobec młodzieży.",
          "Oceniania nie ma."] },
    { u: "tab", t: "mcq",
      q: "Co jest największym oporem u młodzieży?",
      a: ["Lęk przed oceną rówieśników, ironia, „to jest bez sensu”", "Szybkie rozpraszanie uwagi przy każdym nowym zadaniu",
          "Brak cierpliwości do dłuższych i trudniejszych zadań", "Trudność ze znoszeniem frustracji, gdy coś nie wychodzi"],
      x: "Z tabeli: u młodzieży opór to lęk przed oceną rówieśników, ironia i „to jest bez sensu”.",
      w: ["To opór dzieci.",
          "To opór dzieci.",
          "To opór dzieci."] },
    { u: "tab", t: "mcq",
      q: "Co jest największym oporem u dzieci?",
      a: ["Rozpraszanie uwagi, brak cierpliwości, trudność z frustracją", "Ironia wobec zadań, prowadzącego i całej grupy",
          "Lęk przed oceną rówieśników i ich komentarzami", "Postawa „to jest bez sensu” wobec każdego zadania"],
      x: "Z tabeli: u dzieci opór to rozpraszanie uwagi, brak cierpliwości i trudność z frustracją.",
      w: ["Ironia to opór młodzieży.",
          "To opór młodzieży.",
          "To opór młodzieży."] },
    { u: "tab", t: "mcq",
      q: "Jaka jest motywacja dzieci?",
      a: ["Naturalna, wewnętrzna, oparta na zabawie (homo ludens)", "Zależna od poczucia sensu i autonomii w działaniu",
          "Zależna głównie od akceptacji grupy rówieśników", "Oparta przede wszystkim na ocenach i nagrodach"],
      x: "Dzieci motywuje zabawa: naturalnie i od środka (homo ludens, „człowiek bawiący się”).",
      w: ["To motywacja młodzieży.",
          "To ważne u młodzieży.",
          "Ocen nie ma, a dzieci motywuje zabawa."] },
    { u: "tab", t: "mcq",
      q: "Od czego zależy motywacja młodzieży?",
      a: ["Od poczucia sensu i autonomii, z silnym wpływem rówieśników", "Od zabawy, tak samo jak u młodszych dzieci",
          "Od nagród rzeczowych, które dostaje za udział", "Wyłącznie od rodziców i od tego, co oni powiedzą"],
      x: "Z tabeli: młodzież motywuje poczucie sensu i autonomii, a mocno wpływa na nią akceptacja rówieśników.",
      w: ["Zabawa motywuje dzieci.",
          "Nagrody nie były w tabeli.",
          "W tabeli są rówieśnicy, a nie rodzice."] },
    { u: "tab", t: "sort", q: "Rekomendowane techniki: dla kogo?",
      cats: ["Dzieci", "Młodzież"],
      why: ["Dla dzieci: techniki sensoryczne, bajkoterapia, gry ruchowo-twórcze, rysunek.",
            "Dla młodzieży: drama, art journaling, kolaż (manifesty), muzyka, fotografia."],
      items: [
        ["techniki sensoryczne", 0], ["bajkoterapia", 0], ["gry ruchowo-twórcze", 0], ["drama", 1], ["art journaling", 1], ["kolaż (manifesty)", 1],
        ["fotografia", 1]],
      x: "Dzieci: zmysły, bajki, ruch. Młodzież: drama, art journaling, kolaż, muzyka, fotografia." },
    { u: "tab", t: "type", q: "„Człowiek bawiący się” to po łacinie homo…", a: ["ludens"],
      x: "Homo ludens (Huizinga): zabawa to źródło kultury i motywacji dzieci." },
    { u: "tab", t: "mcq", s: "D", q: "Kto jest autorem określenia homo ludens?",
      a: ["J. Huizinga", "D. Elkind", "J. Piaget", "Z. Freud"],
      x: "Johan Huizinga, holenderski historyk kultury, w książce „Homo ludens” (1938).",
      w: ["Elkind to egocentryzm adolescentny.",
          "Piaget to rozwój poznawczy.",
          "Freud to psychoanaliza i sublimacja."] },
    { u: "tab", t: "mcq", s: "U",
      q: "Czym jest vision board?",
      a: ["Kolażem dla młodzieży: zdjęcia podpisane ideami, wartościami lub celami", "Tablicą z ocenami i postępami wszystkich uczestników",
          "Planem zajęć wywieszonym na drzwiach sali na cały semestr", "Techniką sensoryczną dla przedszkolaków, z piaskiem i wodą"],
      x: "Vision board to kolaż-manifest: zdjęcia z podpisami o wartościach i celach. Służy autorefleksji młodzieży.",
      w: ["Ocen nie ma.",
          "To technika twórcza, a nie organizacja zajęć.",
          "To technika dla młodzieży."] },
    { u: "tab", t: "tf", s: "U", q: "Vision board odpowiada celom młodzieży z tabeli: autorefleksji i budowaniu tożsamości.", a: true,
      x: "Tak. Wybierając zdjęcia i podpisy o swoich wartościach i celach, nastolatek myśli o tym, kim jest." },

    /* ---------- Która to zasada? ---------- */
    { u: "mix", t: "which", q: "Psycholog mówi: „Widzę, że użyłeś dużo czerwieni”, zamiast „piękny rysunek”.", a: 1,
      x: "Opis bez oceny estetyki to prymat procesu nad efektem (zasada 1)." },
    { u: "mix", t: "which", q: "Prowadzącego nie interesuje, jak wygląda gotowa praca, tylko jak dziecko pracowało.", a: 1,
      x: "Liczy się proces, a nie efekt (zasada 1)." },
    { u: "mix", t: "which", q: "Nastolatek nie chce pokazać grupie swojego listu. Prowadzący to akceptuje.", a: 2,
      x: "Prawo do odmowy należy do psychologicznego bezpieczeństwa (zasada 2)." },
    { u: "mix", t: "which", q: "Prowadzący docenia nietypowy pomysł w pracy, zamiast wytykać krzywe linie.", a: 2,
      x: "Zielony ołówek: zasoby zamiast błędów. To psychologiczne bezpieczeństwo (zasada 2)." },
    { u: "mix", t: "which", q: "Grupa lepi z gliny przy muzyce, a w sali pachnie lawendą.", a: 3,
      x: "Dotyk, słuch i węch naraz: aktywacja polisensoryczna (zasada 3)." },
    { u: "mix", t: "which", q: "Uczestnicy malują wielkoformatowo na podłodze i dotykają różnych faktur.", a: 3,
      x: "Ciało i wiele zmysłów zamiast biurka: aktywacja polisensoryczna (zasada 3)." },
    { u: "mix", t: "which", q: "Klasa przychodzi po bójce na przerwie. Prowadzący porzuca plan i zajmuje się konfliktem.", a: 4,
      x: "Gotowość na zwroty akcji to elastyczność struktury (zasada 4)." },
    { u: "mix", t: "which", q: "Prowadzący traktuje scenariusz jako punkt wyjścia, a nie obowiązek.", a: 4,
      x: "Scenariusz jako punkt wyjścia to elastyczność struktury (zasada 4)." },
    { u: "mix", t: "which", q: "Dziewczynka opowiada o smutnym potworze, który zgubił się w lesie.", a: 5,
      x: "O swoim smutku mówi przez postać potwora: metaforyzacja i projekcja (zasada 5)." },
    { u: "mix", t: "which", q: "Chłopiec gra zbuntowanego bohatera zamiast mówić wprost o swoich problemach.", a: 5,
      x: "Rola daje bezpieczny dystans: metaforyzacja i projekcja (zasada 5)." },
    { u: "mix", t: "which", q: "Każde zajęcia zaczynają się rundką „jakim kolorem dziś jesteś?”.", a: 6,
      x: "Stały rytuał rozpoczęcia to setting: rytualizacja i ramy (zasada 6)." },
    { u: "mix", t: "which", q: "Ławki lądują pod ścianą, a grupa siada w kręgu na poduszkach.", a: 6,
      x: "Zmiana przestrzeni oddziela zajęcia od zwykłej lekcji: rytualizacja i ramy (zasada 6)." },
    { u: "mix", t: "which", q: "Nastolatek mówi „to jest dla dzieci”. Prowadzący odpowiada, że może po prostu posiedzieć i popatrzeć.", a: 7,
      x: "Przyjęcie oporu z empatią, bez zmuszania: ambiwalencja oporu (zasada 7)." },
    { u: "mix", t: "which", q: "Uczestnicy grają rolę zepsutej zabawki zostawionej na deszczu.", a: 8,
      x: "Wejście w cudzą perspektywę (nawet przedmiotu) to przekraczanie egocentryzmu (zasada 8). Rola daje też dystans, ale ten przykład wykład podał przy zasadzie 8." },
    { u: "mix", t: "which", q: "Uczniowie piszą list z perspektywy swojego nauczyciela.", a: 8,
      x: "Pisanie jako ktoś inny wymusza cudzą perspektywę (zasada 8)." },
    { u: "mix", t: "which", q: "Dziecko maluje niebieską trawę i czarne słońce. Psycholog niczego nie poprawia.", a: 9,
      x: "Decyzje należą do dziecka, co buduje sprawczość (zasada 9)." },
    { u: "mix", t: "which", q: "Każda decyzja w projekcie należy do uczestnika: kolory, postacie, zakończenie.", a: 9,
      x: "„Ja decyduję, ja kreuję”: sprawczość i poczucie kontroli (zasada 9)." },
    { u: "mix", t: "which", q: "Wściekły nastolatek uderza w ciężką glinę i z niej rzeźbi.", a: 10,
      x: "Złość dostaje twórczy kierunek: kanalizacja i sublimacja (zasada 10). Glina angażuje też zmysły, ale tu chodzi o złość." },
    { u: "mix", t: "which", q: "Nadaktywne dziecko zamienia swój ruch w ekspresyjny taniec.", a: 10,
      x: "Ruch nie jest wygaszany, tylko kierowany: kanalizacja (zasada 10)." },
    { u: "mix", t: "which", q: "Nastolatka pisze tekst piosenki pełen buntu i ostrych słów.", a: 10,
      x: "Bunt zamieniony w tekst piosenki to sublimacja (zasada 10)." },
    { u: "mix", t: "mcq",
      q: "Który element NIE należy do 10 elementów specyfiki pracy twórczej?",
      a: ["Rywalizacja i ranking najlepszych prac", "Ambiwalencja oporu", "Rytualizacja i ramy czasowo-przestrzenne", "Aktywacja polisensoryczna"],
      x: "Rywalizacja i rankingi to ocenianie, a zasada 2 każe je zawiesić. Pozostałe trzy to zasady 7, 6 i 3.",
      w: ["To zasada 7, więc należy do listy.",
          "To zasada 6, więc należy do listy.",
          "To zasada 3, więc należy do listy."] },
    { u: "mix", t: "mcq", q: "Ile elementów specyfiki pracy twórczej z dziećmi i młodzieżą omówiono na wykładzie?",
      a: ["10", "7", "5", "12"],
      x: "Dziesięć: od prymatu procesu (1) do kanalizacji i sublimacji (10).",
      w: ["Za mało: zasad było 10.",
          "Za mało: zasad było 10.",
          "Za dużo: zasad było 10."] }
  ],
  sortDecks: [
    { id: "wiek", title: "Dzieci czy młodzież?", sub: "Tabela różnic: cele, motywacja, rola, opór, techniki",
      cats: ["Dzieci", "Młodzież"],
      why: ["To z kolumny „dzieci” w tabeli: zmysły, ciekawość, zabawa, krótka uwaga, techniki sensoryczne i bajki.",
            "To z kolumny „młodzież” w tabeli: tożsamość, autorefleksja, sens i autonomia, rówieśnicy, ironia, drama i kolaż."],
      items: [
        ["rozwój sensoryczny", 0], ["ciekawość", 0], ["przełamywanie schematów poznawczych", 0], ["motywacja oparta na zabawie (homo ludens)", 0],
        ["towarzysz w zabawie", 0],
        ["facylitator, animator dostarczający bodźców", 0, "Rola prowadzącego wobec dzieci: towarzysz w zabawie, facylitator, animator."],
        ["szybkie rozpraszanie uwagi", 0], ["brak cierpliwości", 0], ["trudność z frustracją", 0], ["techniki sensoryczne", 0], ["bajkoterapia", 0],
        ["gry ruchowo-twórcze", 0],
        ["rysunek i malowanie", 0, "W tabeli rysunek i malowanie są wśród technik dla dzieci."],
        ["autorefleksja", 1], ["budowanie tożsamości", 1],
        ["kanalizowanie trudnych emocji", 1, "W tabeli to cel pracy z młodzieżą, obok autorefleksji i budowania tożsamości."],
        ["motywacja zależna od poczucia sensu i autonomii", 1], ["silny wpływ akceptacji rówieśniczej", 1], ["partner w dyskusji", 1],
        ["świadek procesu", 1, "Rola prowadzącego wobec młodzieży: partner w dyskusji, świadek procesu, gwarant poufności."],
        ["gwarant poufności i bezpieczeństwa", 1], ["lęk przed oceną rówieśników", 1], ["ironia", 1], ["postawa „to jest bez sensu”", 1], ["drama", 1],
        ["art journaling", 1], ["kolaż (manifesty)", 1],
        ["muzyka", 1, "W tabeli muzyka stoi wśród technik dla młodzieży, razem z dramą, art journalingiem, kolażem i fotografią."],
        ["fotografia", 1],
        ["vision board", 1, "Vision board to kolaż-manifest, czyli technika dla młodzieży (autorefleksja, tożsamość)."]] },
    { id: "olowek", title: "Zielony czy czerwony ołówek?", sub: "Tak robi psycholog albo tak nie robi",
      cats: ["Czerwony: błąd", "Zielony: dobrze"],
      why: ["Tak psycholog nie robi: ocenia, poprawia, zmusza albo tłumi, zamiast nadać kierunek.",
            "Tak robi psycholog: opisuje zamiast oceniać, wzmacnia zasoby, szanuje odmowę i daje dziecku decyzje."],
      items: [
        ["„Widzę, że użyłeś dużo czerwieni. Opowiesz mi o tym?”", 1, "Opis bez oceny i zaproszenie do opowieści (zasada 1)."],
        ["„Opowiedz mi o tym misiu. O czym on myśli?”", 1, "Pytanie otwarte uruchamia projekcję: mówiąc o misiu, dziecko mówi o sobie (zasada 1)."],
        ["Docenia nietypowy pomysł w pracy", 1, "Zielony ołówek: wzmacnia zasoby (zasada 2)."],
        ["Akceptuje, że uczestnik nie chce pokazać pracy", 1, "Prawo do odmowy (zasada 2)."],
        ["„Masz prawo uważać to za nudne. Możesz posiedzieć i popatrzeć.”", 1, "Przyjmuje opór z empatią, bez zmuszania (zasada 7)."],
        ["Porzuca plan, gdy grupa przychodzi skłócona", 1, "Elastyczność struktury i gotowość na zwroty akcji (zasada 4)."],
        ["Zaczyna zajęcia rundką „jakim kolorem dziś jesteś?”", 1, "Rytuał rozpoczęcia, czyli setting (zasada 6)."],
        ["Akceptuje czarne słońce i zastanawia się, skąd ten wybór", 1, "Decyzja należy do dziecka, a kolor może coś mówić o jego przeżyciach (zasada 9)."],
        ["Daje złemu nastolatkowi glinę do uderzania", 1, "Kanalizacja: złość dostaje twórczy kierunek (zasada 10)."],
        ["Zamienia ruch nadaktywnego dziecka w taniec", 1, "Kanalizacja: ruch zamieniony w ekspresję (zasada 10)."],
        ["Odsuwa ławki i sadza grupę w kręgu", 1, "Zmiana przestrzeni oddziela zajęcia od zwykłej lekcji (zasada 6)."],
        ["Łączy glinę z muzyką i zapachami", 1, "Aktywacja polisensoryczna (zasada 3)."],
        ["„Piękny rysunek, super!”", 0, "To ocena estetyki. Psycholog opisuje, co widzi, zamiast chwalić wygląd (zasada 1)."],
        ["„Co dostałeś z kartkówki?”", 0, "Nastawienie na efekt (ocenę), a nie na proces (zasada 1)."],
        ["„Hej, słońce nie jest czarne”", 0, "Poprawianie odbiera dziecku decyzję. Tak zrobiłby nauczyciel plastyki, nie psycholog (zasada 9)."],
        ["Zaznacza na czerwono, co nie wyszło", 0, "Czerwony ołówek: wytykanie błędów zamiast wzmacniania zasobów (zasada 2)."],
        ["Każe wszystkim pokazać prace grupie", 0, "Łamie prawo do odmowy (zasada 2)."],
        ["„Wszyscy robią, więc ty też musisz”", 0, "Walka z oporem zamiast empatii (zasada 7)."],
        ["Trzyma się scenariusza mimo kryzysu w grupie", 0, "Sztywny scenariusz to największy wróg kreatywności (zasada 4)."],
        ["Ucisza nadaktywne dziecko", 0, "Wygasza ruch, zamiast nadać mu kierunek, np. w tańcu (zasada 10)."],
        ["Tłumi agresję nastolatka karą", 0, "Zamiast kary: glina do uderzania albo buntowniczy tekst piosenki (zasada 10)."],
        ["Ocenia estetykę gotowego dzieła", 0, "Liczy się proces, a nie wygląd dzieła (zasada 1)."],
        ["Prowadzi zajęcia tylko przy biurkach, na samym myśleniu pojęciowym", 0, "Brak zakotwiczenia w ciele. Zasada 3 każe angażować zmysły."],
        ["Wygasza napięcie zamiast nadać mu kierunek", 0, "Zadaniem psychologa jest nadać napięciu kierunek, a nie je wygasić (zasada 10)."]] },
    { id: "loc", title: "Kontrola wewnętrzna czy zewnętrzna?", sub: "Zasada 9: rozpoznaj umiejscowienie kontroli",
      cats: ["Zewnętrzna", "Wewnętrzna"],
      why: ["Wynik zależy od losu albo od innych: to kontrola zewnętrzna.",
            "Wynik zależy ode mnie: to kontrola wewnętrzna."],
      items: [
        ["„To zależy ode mnie.”", 1], ["„Ja decyduję, ja kreuję.”", 1], ["„Mój głos ma znaczenie.”", 1],
        ["„Jak się przygotuję, to zdam.”", 1, "Wynik zależy od mojego wysiłku, więc kontrola jest wewnętrzna."],
        ["„Mogę coś zmienić.”", 1],
        ["„Mój wybór, moje słońce.”", 1, "Decyzja należy do mnie, jak w zasadzie 9 (czarne słońce)."],
        ["„Nie mam na nic wpływu.”", 0], ["„Ktoś steruje moim losem.”", 0], ["„Decydują za mnie.”", 0], ["„To kwestia szczęścia.”", 0],
        ["„I tak wszystko zależy od innych.”", 0],
        ["„Macie się dostosować i tyle.”", 0, "Ktoś narzuca ramy, a ty nie masz na nie wpływu: to głos kontroli zewnętrznej."]] }
  ],

  /* Pomoc pamięciowa do 10 zasad (★ nie z wykładu). */
  story: { title: "10 zasad w jednej scenie", extra: true, ordered: true,
    intro: "★ Pomoc pamięciowa, nie z wykładu. Wyobraź sobie jedne zajęcia od wejścia do wyjścia:", items: [
    ["Proces", "Dziecko rysuje, a nikt nie pyta, na ile to jest."],
    ["Bezpieczeństwo", "Na stole leży tylko zielony ołówek. Czerwony został w szufladzie."],
    ["Zmysły", "Pachnie glina, gra muzyka, farba ląduje na podłodze."],
    ["Elastyczność", "Wpada skłócona klasa, więc scenariusz idzie do kosza."],
    ["Metafora", "Zamiast o sobie dzieci opowiadają o smutnym potworze w lesie."],
    ["Rytuał", "Ławki pod ścianą, krąg na poduszkach, iskierka przyjaźni."],
    ["Opór", "W kącie siedzi nastolatek: „to jest bez sensu”. Może sobie popatrzeć."],
    ["Perspektywa", "Ktoś gra zepsutą zabawkę zostawioną na deszczu."],
    ["Sprawczość", "Na rysunku wschodzi czarne słońce i nikt go nie poprawia."],
    ["Sublimacja", "Na koniec ktoś wali pięścią w glinę, a nie w kolegę."]
  ] },

  /* Notatki do czytania. Klasy: .oral = ustnie, .extra = dopowiedzenie (★). */
  notes: [
    { id: "intro", title: "O czym jest ten wykład", html:
      "<p>Wykład otwiera kurs (temat 1 z sylabusa). Pokazuje uniwersalne elementy, które odróżniają zajęcia twórcze z dziećmi i młodzieżą od standardowej edukacji i od pracy z dorosłymi. Prowadząca nazywa je <b>kluczowymi zasadami psychopedagogicznymi</b>, które każdy przyszły psycholog powinien wdrożyć w praktyce.</p>" +
      "<p><b>Zaliczenie:</b> obecność plus egzamin, czyli test pisemny z pytaniami zamkniętymi. Trzeba uzyskać <b>więcej niż 50%</b> punktów.</p>" +
      "<div class='oral'><p><b>Facylitacja</b> to sytuacja, w której obecność psychologa umożliwia rozpoczęcie i kontynuowanie procesu rozmawiania o trudnych emocjach. Obok facylitacji prowadząca wprowadziła pojęcie socjoterapii.</p></div>" +
      "<aside class='extra'><p>Termin „facylitator” spopularyzował m.in. <b>Carl Rogers</b> w nurcie humanistycznym. Facylitator nie jest ekspertem, który „naprawia”. Tworzy warunki, w których proces może zajść sam.</p>" +
      "<p><b>Socjoterapia</b> to grupowa forma pomocy psychologicznej dla dzieci i młodzieży z trudnościami emocjonalnymi i w relacjach. Opiera się na doświadczeniach korektywnych. Cele: terapeutyczne (odreagowanie, korekta przekonań), edukacyjne (umiejętności społeczne, komunikacja) i rozwojowe. Metody twórcze (rysunek, drama, ruch) są jej podstawowym narzędziem. W Polsce spopularyzowała ją m.in. K. Sawicka.</p></aside>" },
    { id: "p1", n: 1, title: "Prymat procesu nad efektem", html:
      "<p>Paradygmat <b>„tu i teraz”</b>. U dorosłych często liczy się produkt końcowy (książka, obraz, projekt). U dzieci i młodzieży największą wartość terapeutyczną i rozwojową ma <b>sam akt tworzenia</b>.</p>" +
      "<p>Psycholog nie ocenia estetyki dzieła. Zamiast „piękny rysunek” czy „super” mówi:</p>" +
      "<blockquote>„Widzę, że użyłeś dużo czerwieni i mocno naciskałeś kredkę (opowiesz mi o tym?)”</blockquote>" +
      "<p><b>Cel:</b> uwolnienie od presji perfekcjonizmu.</p>" +
      "<div class='oral'><ul><li>„Co dostałeś z kartkówki?” to typowe nastawienie dorosłych na wynik zamiast na to, jak dziecko pracowało.</li>" +
      "<li>„Wylewanie dziecka z kąpielą”: oceniając tylko efekt, tracimy to, co w pracy twórczej najcenniejsze.</li>" +
      "<li>Pytanie otwarte („opowiedz mi o tym misiu, o czym on myśli?”) uruchamia <b>projekcję</b>: mówiąc o misiu, dziecko mówi o sobie.</li>" +
      "<li><b>Projekcja myśli</b> to przypisywanie obiektowi zewnętrznemu własnych stanów wewnętrznych.</li></ul></div>" +
      "<aside class='extra'><p>W psychoanalizie projekcja to mechanizm obronny. Tu chodzi o sens z technik projekcyjnych, bez założenia obrony. Na teście trzymaj się definicji z wykładu.</p></aside>" },
    { id: "p2", n: 2, title: "Psychologiczne bezpieczeństwo", html:
      "<p>Twórczość wymaga odsłonięcia się, a to ryzyko emocjonalne (szczególnie u młodzieży). Specyfika tych zajęć to <b>całkowite zawieszenie krytyki i ocen szkolnych</b>.</p>" +
      "<p><b>Zasada zielonego ołówka:</b> zamiast wytykać błędy (czerwony ołówek) psycholog zauważa i wzmacnia to, co unikalne, nietypowe i ciekawe. Hasło ze slajdu: <mark>ZASOBY</mark>.</p>" +
      "<p><b>Prawo do odmowy:</b> uczestnik zawsze może powiedzieć „NIE” i nie pokazywać pracy grupie.</p>" +
      "<div class='oral'><p>„Nie da się uciec od oceniania”, więc psycholog świadomie zmienia jej <b>kierunek</b>: zasoby, nie błędy.</p></div>" +
      "<aside class='extra'><p>„Zielony ołówek” jest znany z oceniania kształtującego. Łączy się z tematem 4 (etyka oceniania wytworów).</p></aside>" },
    { id: "p3", n: 3, title: "Aktywacja polisensoryczna", html:
      "<p>W dobie przebodźcowania cyfrowego dzieci i młodzież potrzebują <b>zakotwiczenia w ciele</b>. Praca twórcza nie może opierać się wyłącznie na myśleniu pojęciowym.</p>" +
      "<p>Przykłady: glina przy muzyce, malowanie wielkoformatowe na podłodze, zapachy, faktury (multi-sensory environments).</p>" +
      "<p><b>Efekt:</b> regulacja układu nerwowego i łatwiejsza ekspresja dla osób, którym trudno mówić o emocjach.</p>" +
      "<div class='oral'><p>Samo siedzenie przy biurku to praca wyłącznie na myśleniu pojęciowym.</p></div>" +
      "<aside class='extra'><p>Najbardziej znana realizacja: <b>Snoezelen</b>, sala doświadczania świata z Holandii.</p></aside>" },
    { id: "p4", n: 4, title: "Elastyczność struktury", html:
      "<p><b>Sztywny scenariusz zajęć jest największym wrogiem kreatywności.</b> Prowadzący musi być gotowy na <mark>ZWROTY AKCJI</mark>.</p>" +
      "<p>Jeśli zaplanowałeś bajkę o lęku, a grupa wchodzi poruszona konfliktem w klasie, porzucasz plan i zamieniasz metodę w narzędzie do przepracowania kryzysu. Twórczość staje się <b>wentylem bezpieczeństwa</b>.</p>" +
      "<div class='oral'><p>Scenariusz jest punktem wyjścia, a nie obowiązkiem.</p></div>" },
    { id: "p5", n: 5, title: "Metaforyzacja i projekcja", html:
      "<p>Dzieciom i młodzieży trudno mówić wprost o lękach, kompleksach i traumach, więc korzystamy z narzędzi projekcyjnych.</p>" +
      "<p>Łatwiej opowiedzieć o „smutnym potworze, który zgubił się w lesie” (bajkoterapia) albo zagrać zbuntowanego bohatera (drama), niż powiedzieć „czuję się samotny i nierozumiany przez rodziców”. <b>Metafora i symbolika dają dziecku bezpieczeństwo.</b></p>" },
    { id: "p6", n: 6, title: "Rytualizacja i ramy czasowo-przestrzenne", html:
      "<p>Jasne granice oddzielają przestrzeń twórczą od „zwykłej rzeczywistości”. Hasło ze slajdu: <mark>SETTING</mark>.</p>" +
      "<p>Stałe rytuały rozpoczęcia (Iskierka przyjaźni, rundka „jakim kolorem dziś jesteś?”) i zakończenia. Fizyczna zmiana przestrzeni: odsunięte ławki, krąg na poduszkach.</p>" +
      "<aside class='extra'><p>Iskierka przyjaźni: uczestnicy w kręgu kolejno przekazują sobie uścisk dłoni. Setting w psychoterapii: stałe ramy spotkań, czyli miejsce, czas i zasady.</p></aside>" },
    { id: "p7", n: 7, title: "Ambiwalencja oporu", html:
      "<p>U dorosłych opór pojawia się rzadko (ale bywa zakamuflowany). U dzieci, a zwłaszcza młodzieży, <b>opór jest naturalnym elementem procesu</b>.</p>" +
      "<p>Za tekstami „to jest dla dzieci”, „nie umiem rysować” kryje się <b>lęk</b> przed oceną, odrzuceniem przez grupę lub trudnymi emocjami. Psycholog nie walczy i nie zmusza:</p>" +
      "<blockquote>„Masz prawo uważać to zadanie za nudne. Możesz po prostu posiedzieć z nami i popatrzeć.”</blockquote>" +
      "<p>Młodzież bez nacisku często po kilkunastu minutach sama dołącza.</p>" +
      "<div class='oral'><p>Opór jest normalny i uczestnik ma do niego prawo. To łączy się z prawem do odmowy (zasada 2).</p></div>" },
    { id: "p8", n: 8, title: "Egocentryzm i teoria umysłu", html:
      "<p>Grupowa praca twórcza (drama, wspólny scenariusz) to trening społeczny. Młodsze dzieci tkwią w <b>egocentryzmie poznawczym</b>, młodzież w <b>egocentryzmie adolescentnym</b>.</p>" +
      "<p>Zadania wymuszają cudzą perspektywę: „zagraj zepsutą zabawkę zostawioną na deszczu”, „napisz list z perspektywy nauczyciela”. Buduje to empatię i elastyczność poznawczą.</p>" +
      "<div class='oral'><ul><li>Poznawczy: dziecko oczekuje, że wszyscy znają zasady, które samo wymyśliło.</li>" +
      "<li>Afektywny: „idę na imprezę z pryszczem, to wina świata”.</li>" +
      "<li>Marki (np. kosmetyczne) budują warunki, w których odbiorca projektuje na siebie przeżycie.</li></ul></div>" +
      "<aside class='extra'><p>Poznawczy opisał <b>Piaget</b> (stadium przedoperacyjne), adolescentny <b>Elkind</b>: wyobrażona publiczność i baśń osobista. Teoria umysłu to przypisywanie innym stanów psychicznych odmiennych od własnych. Na teście używaj nazwy ze slajdu: <b>egocentryzm adolescentny</b>.</p></aside>" },
    { id: "p9", n: 9, title: "Sprawczość i poczucie kontroli (LOC)", html:
      "<p>Wielu młodych ludzi z trudnościami czuje, że nie ma wpływu na swoje życie (<b>zewnętrzne umiejscowienie kontroli</b>).</p>" +
      "<p>Czysta kartka, glina czy pusta scena dają dziecku absolutną władzę nad tworzonym światem. Każda decyzja należy do młodego człowieka. Czarne słońce i niebieska trawa? Akceptujemy.</p>" +
      "<blockquote>„Ja decyduję, ja kreuję, mój głos ma znaczenie.”</blockquote>" +
      "<div class='oral'><p>Nauczyciel plastyki poprawi czarne słońce. Psycholog zastanowi się, dlaczego dziecko tak namalowało. Ważne jest też, jak ktoś przeżywa narzucone ramy.</p></div>" +
      "<aside class='extra'><p>LOC to koncepcja <b>J. Rottera</b>. Internalizacja: od „decydują za mnie” do „to zależy ode mnie”.</p></aside>" },
    { id: "p10", n: 10, title: "Kanalizacja i sublimacja", html:
      "<p>Dzieci i młodzież noszą w sobie napięcie, złość, lęk, energię seksualną. Według nurtu psychodynamicznego twórczość jest <b>najwyższą formą obrony przed lękiem (sublimacją)</b>: zamienia destrukcyjną energię w wytwór.</p>" +
      "<p>Agresja? Ciężka glina do uderzania albo buntowniczy tekst piosenki. Nadaktywność? Ekspresyjny taniec.</p>" +
      "<div class='oral'><p>Zadaniem psychologa nie jest wygaszenie napięcia, lecz nadanie mu kierunku.</p></div>" +
      "<aside class='extra'><p>Sublimację opisał <b>Freud</b>. <b>Vaillant</b> zalicza ją do mechanizmów dojrzałych.</p></aside>" }
  ],

  table: {
    title: "Dzieci a młodzież",
    head: ["Wymiar", "Dzieci", "Młodzież"],
    rows: [
      ["Główny cel", "rozwój sensoryczny, ciekawość, przełamywanie schematów poznawczych", "autorefleksja, budowanie tożsamości, kanalizowanie trudnych emocji"],
      ["Motywacja", "naturalna, wewnętrzna, oparta na zabawie (homo ludens)", "zależna od poczucia sensu i autonomii; silny wpływ akceptacji rówieśniczej"],
      ["Rola prowadzącego", "towarzysz w zabawie, facylitator, animator dostarczający bodźców", "partner w dyskusji, świadek procesu, gwarant poufności i bezpieczeństwa"],
      ["Największy opór", "szybkie rozpraszanie uwagi, brak cierpliwości, trudność z frustracją", "lęk przed oceną rówieśników, ironia, postawa „to jest bez sensu”"],
      ["Techniki", "techniki sensoryczne, bajkoterapia, gry ruchowo-twórcze, rysunek, malowanie", "drama, art journaling, kolaż (manifesty), muzyka, fotografia"]
    ]
  }
});
